# ============================================================
# QUICK CSV IMPORT - Commissions MVP Demo
# ============================================================
# Purpose: Load 4 CSV files into database for demo
# Time: 10-15 minutes
# ============================================================

$ErrorActionPreference = "Stop"

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "QUICK CSV IMPORT - Commissions MVP" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Paths
$importDir = "$PSScriptRoot\import_templates"
$outputSql = "$PSScriptRoot\GENERATED_IMPORT.sql"

Write-Host "📂 Import Directory: $importDir" -ForegroundColor Yellow
Write-Host "📄 Output SQL: $outputSql" -ForegroundColor Yellow
Write-Host ""

# Check files exist
$files = @(
    "01_parties.csv",
    "02_investors.csv",
    "03_agreements.csv",
    "04_contributions.csv"
)

foreach ($file in $files) {
    $path = Join-Path $importDir $file
    if (-not (Test-Path $path)) {
        Write-Host "❌ Missing file: $file" -ForegroundColor Red
        exit 1
    }
    Write-Host "✅ Found: $file" -ForegroundColor Green
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "GENERATING SQL..." -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Start SQL generation
$sql = @"
-- ============================================================
-- QUICK IMPORT - Generated $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
-- ============================================================
-- Purpose: Import CSV data for Commissions MVP demo
-- Generated by: QUICK_IMPORT.ps1
-- ============================================================

BEGIN;

-- ============================================================
-- STEP 1: Import Parties
-- ============================================================

"@

# Load and process parties
Write-Host "📋 Processing parties..." -ForegroundColor Yellow
$parties = Import-Csv -Path (Join-Path $importDir "01_parties.csv")
$partyCount = 0

foreach ($party in $parties) {
    $name = $party.party_name.Replace("'", "''")
    $email = if ($party.contact_email) { $party.contact_email.Replace("'", "''") } else { "" }
    $paymentMethod = if ($party.payment_method) { $party.payment_method.Replace("'", "''") } else { "Invoice" }

    if ($name) {
        $sql += @"

INSERT INTO parties (name, contact_email, kind, payment_method, status)
VALUES ('$name', $(if($email){"'$email'"}else{"NULL"}), 'DISTRIBUTOR', '$paymentMethod', 'ACTIVE')
ON CONFLICT (name) DO UPDATE
SET contact_email = COALESCE(EXCLUDED.contact_email, parties.contact_email),
    payment_method = EXCLUDED.payment_method;

"@
        $partyCount++
    }
}

Write-Host "  ✅ $partyCount parties queued" -ForegroundColor Green

# ============================================================
# STEP 2: Import Investors
# ============================================================

$sql += @"

-- ============================================================
-- STEP 2: Import Investors
-- ============================================================

"@

Write-Host "📋 Processing investors..." -ForegroundColor Yellow
$investors = Import-Csv -Path (Join-Path $importDir "02_investors.csv")
$investorCount = 0

foreach ($investor in $investors) {
    $name = $investor.investor_name.Replace("'", "''")
    $introducedBy = if ($investor.introduced_by) { $investor.introduced_by.Replace("'", "''") } else { "" }
    $email = if ($investor.email) { $investor.email.Replace("'", "''") } else { "" }

    if ($name -and $name -ne "Totals") {  # Skip "Totals" row
        $sql += @"

INSERT INTO investors (name, email, introduced_by, status)
VALUES (
    '$name',
    $(if($email){"'$email'"}else{"NULL"}),
    $(if($introducedBy){"(SELECT id FROM parties WHERE name = '$introducedBy' LIMIT 1)"}else{"NULL"}),
    'ACTIVE'
)
ON CONFLICT (name) DO UPDATE
SET email = COALESCE(EXCLUDED.email, investors.email),
    introduced_by = COALESCE(EXCLUDED.introduced_by, investors.introduced_by);

"@
        $investorCount++
    }
}

Write-Host "  ✅ $investorCount investors queued" -ForegroundColor Green

# ============================================================
# STEP 3: Import Agreements
# ============================================================

$sql += @"

-- ============================================================
-- STEP 3: Import Agreements (Commission Agreements)
-- ============================================================

"@

Write-Host "📋 Processing agreements..." -ForegroundColor Yellow
$agreements = Import-Csv -Path (Join-Path $importDir "03_agreements.csv")
$agreementCount = 0

foreach ($agreement in $agreements) {
    $partyName = $agreement.party_name.Replace("'", "''")
    $dealName = $agreement.deal_name.Replace("'", "''")
    $rateBps = [int]$agreement.rate_bps
    $vatMode = if ($agreement.vat_mode) { $agreement.vat_mode } else { "on_top" }
    $vatRate = [decimal]$agreement.vat_rate
    $effectiveFrom = if ($agreement.effective_from) { $agreement.effective_from } else { "2020-01-01" }
    $effectiveTo = if ($agreement.effective_to) { $agreement.effective_to } else { "NULL" }

    if ($partyName -and $dealName) {
        $snapshot = @"
{
  \"kind\": \"distributor_commission\",
  \"party_name\": \"$partyName\",
  \"deal_name\": \"$dealName\",
  \"terms\": [{
    \"from\": \"$effectiveFrom\",
    \"to\": $($if($effectiveTo -eq "NULL"){"null"}else{"\"$effectiveTo\""}),
    \"rate_bps\": $rateBps,
    \"vat_mode\": \"$vatMode\",
    \"vat_rate\": $vatRate
  }]
}
"@

        $sql += @"

INSERT INTO agreements (
    party_id,
    deal_id,
    scope,
    kind,
    status,
    snapshot_json,
    created_at,
    updated_at
)
SELECT
    p.id as party_id,
    d.id as deal_id,
    'DEAL' as scope,
    'distributor_commission' as kind,
    'APPROVED' as status,
    '$($snapshot.Replace("'", "''"))'::jsonb as snapshot_json,
    now() as created_at,
    now() as updated_at
FROM parties p
CROSS JOIN deals d
WHERE p.name = '$partyName'
  AND d.name = '$dealName'
ON CONFLICT DO NOTHING;

"@
        $agreementCount++
    }
}

Write-Host "  ✅ $agreementCount agreements queued" -ForegroundColor Green

# ============================================================
# STEP 4: Import Contributions
# ============================================================

$sql += @"

-- ============================================================
-- STEP 4: Import Contributions
-- ============================================================

"@

Write-Host "📋 Processing contributions..." -ForegroundColor Yellow
$contributions = Import-Csv -Path (Join-Path $importDir "04_contributions.csv")
$contributionCount = 0

foreach ($contribution in $contributions) {
    $investorName = $contribution.investor_name.Replace("'", "''")
    $dealName = $contribution.deal_name.Replace("'", "''")
    $amount = [decimal]$contribution.amount
    $paidInDate = if ($contribution.paid_in_date) { $contribution.paid_in_date } else { "2020-01-01" }

    if ($investorName -and $dealName -and $amount -gt 0) {
        $sql += @"

INSERT INTO contributions (
    investor_id,
    deal_id,
    amount,
    currency,
    paid_in_date,
    status,
    created_at,
    updated_at
)
SELECT
    i.id as investor_id,
    d.id as deal_id,
    $amount as amount,
    'USD' as currency,
    '$paidInDate'::date as paid_in_date,
    'CONFIRMED' as status,
    now() as created_at,
    now() as updated_at
FROM investors i
CROSS JOIN deals d
WHERE i.name = '$investorName'
  AND d.name = '$dealName'
ON CONFLICT DO NOTHING;

"@
        $contributionCount++
    }
}

Write-Host "  ✅ $contributionCount contributions queued" -ForegroundColor Green

# Finish SQL
$sql += @"

-- ============================================================
-- COMMIT
-- ============================================================

COMMIT;

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

-- Count imported records
SELECT 'Parties' as table_name, COUNT(*) as count FROM parties WHERE status = 'ACTIVE'
UNION ALL
SELECT 'Investors', COUNT(*) FROM investors WHERE status = 'ACTIVE'
UNION ALL
SELECT 'Agreements (Commission)', COUNT(*) FROM agreements WHERE kind = 'distributor_commission'
UNION ALL
SELECT 'Contributions', COUNT(*) FROM contributions;

-- Check investor→party links
SELECT
    COUNT(*) as investors_with_party,
    COUNT(*) FILTER (WHERE introduced_by IS NULL) as without_party
FROM investors;

-- Check agreement→deal resolution
SELECT COUNT(*) as commission_agreements
FROM agreements
WHERE kind = 'distributor_commission' AND deal_id IS NOT NULL;

-- ✅ SUCCESS: Data imported
-- Next: Run 03_compute_commissions.ps1

"@

# Write SQL file
$sql | Out-File -FilePath $outputSql -Encoding UTF8

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "✅ SQL GENERATED" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  • Parties: $partyCount" -ForegroundColor Gray
Write-Host "  • Investors: $investorCount" -ForegroundColor Gray
Write-Host "  • Agreements: $agreementCount" -ForegroundColor Gray
Write-Host "  • Contributions: $contributionCount" -ForegroundColor Gray
Write-Host ""
Write-Host "📄 SQL File: $outputSql" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Open Supabase SQL Editor:" -ForegroundColor Gray
Write-Host "     https://supabase.com/dashboard/project/qwgicrdcoqdketqhxbys/sql/new" -ForegroundColor Cyan
Write-Host ""
Write-Host "  2. Open generated file: $outputSql" -ForegroundColor Gray
Write-Host ""
Write-Host "  3. Copy all contents and paste into Supabase" -ForegroundColor Gray
Write-Host ""
Write-Host "  4. Click 'Run' or press Ctrl+Enter" -ForegroundColor Gray
Write-Host ""
Write-Host "  5. Verify the counts match expected values" -ForegroundColor Gray
Write-Host ""
Write-Host "✅ Ready to import!" -ForegroundColor Green
