-- ============================================
-- Load Investors and Deals from CSV
-- Generated: 2025-10-16 15:09:07
-- Source: INVESTOR_ROLLUP_from_DETAILS.csv
-- ============================================

-- ============================================
-- INSERT INVESTORS
-- ============================================
INSERT INTO investors (name, currency, is_gp, notes)
VALUES
  ('Itay Goren', 'USD', false, 'Imported from CSV'),
  ('Tsahi Weiss', 'USD', false, 'Imported from CSV'),
  ('Meitav team Meitav IRA Funds', 'USD', false, 'Imported from CSV'),
  ('Michael Kessel', 'USD', false, 'Imported from CSV'),
  ('Eyal Slimak', 'USD', false, 'Imported from CSV'),
  ('Pinchas Ginsburg', 'USD', false, 'Imported from CSV'),
  ('Shai Sheffer', 'USD', false, 'Imported from CSV'),
  ('Ilan Tamir', 'USD', false, 'Imported from CSV'),
  ('Phoenix team Phoenix', 'USD', false, 'Imported from CSV'),
  ('Amir Shapira', 'USD', false, 'Imported from CSV'),
  ('Ronnie Botton', 'USD', false, 'Imported from CSV'),
  ('Roberto Slimak', 'USD', false, 'Imported from CSV'),
  ('Tsur Moses', 'USD', false, 'Imported from CSV'),
  ('Barak Matalon', 'USD', false, 'Imported from CSV'),
  ('Michael Mann', 'USD', false, 'Imported from CSV'),
  ('Gilad Rabina', 'USD', false, 'Imported from CSV'),
  ('David Kirschenbaum', 'USD', false, 'Imported from CSV'),
  ('Omer Gattenio', 'USD', false, 'Imported from CSV'),
  ('Yoram Dvash', 'USD', false, 'Imported from CSV'),
  ('Yaron Spector', 'USD', false, 'Imported from CSV'),
  ('Yehuda Alon', 'USD', false, 'Imported from CSV'),
  ('Noga Peer', 'USD', false, 'Imported from CSV'),
  ('Yury Sofman', 'USD', false, 'Imported from CSV'),
  ('Zur Erez', 'USD', false, 'Imported from CSV'),
  ('Daniel Basch', 'USD', false, 'Imported from CSV'),
  ('Isaac Zinger', 'USD', false, 'Imported from CSV'),
  ('Zecharia Oren', 'USD', false, 'Imported from CSV'),
  ('Ofir Fishof', 'USD', false, 'Imported from CSV'),
  ('Lior Cohen', 'USD', false, 'Imported from CSV'),
  ('Roni Ashuri', 'USD', false, 'Imported from CSV'),
  ('Ishai Cohen', 'USD', false, 'Imported from CSV'),
  ('Guy Kedar', 'USD', false, 'Imported from CSV'),
  ('Nadav Shachar', 'USD', false, 'Imported from CSV'),
  ('Dror Erez', 'USD', false, 'Imported from CSV'),
  ('Tal Simchony', 'USD', false, 'Imported from CSV'),
  ('Yuval Stern', 'USD', false, 'Imported from CSV'),
  ('Daniel Glinert', 'USD', false, 'Imported from CSV'),
  ('Yaron Haramati', 'USD', false, 'Imported from CSV'),
  ('Steven Ball', 'USD', false, 'Imported from CSV'),
  ('Shimon Gesundheit', 'USD', false, 'Imported from CSV'),
  ('Guy Moses', 'USD', false, 'Imported from CSV'),
  ('David Katz', 'USD', false, 'Imported from CSV'),
  ('Ehud Shabtai', 'USD', false, 'Imported from CSV'),
  ('Amir Shinar', 'USD', false, 'Imported from CSV'),
  ('Eddy Hassid', 'USD', false, 'Imported from CSV'),
  ('Rachel Even Chen', 'USD', false, 'Imported from CSV'),
  ('Sam Rabina', 'USD', false, 'Imported from CSV'),
  ('Eliezer Stern', 'USD', false, 'Imported from CSV'),
  ('Lior Wolf', 'USD', false, 'Imported from CSV'),
  ('Itzhak Miron', 'USD', false, 'Imported from CSV'),
  ('Yosef Stern', 'USD', false, 'Imported from CSV'),
  ('Shachar Levy', 'USD', false, 'Imported from CSV'),
  ('Maria Renault', 'USD', false, 'Imported from CSV'),
  ('David Reichman', 'USD', false, 'Imported from CSV'),
  ('Yakov Bar', 'USD', false, 'Imported from CSV'),
  ('Roni Eiger', 'USD', false, 'Imported from CSV'),
  ('Gil Haramati', 'USD', false, 'Imported from CSV'),
  ('Jacob Cohen', 'USD', false, 'Imported from CSV'),
  ('Gino Borges', 'USD', false, 'Imported from CSV'),
  ('Ido Bukspan', 'USD', false, 'Imported from CSV'),
  ('Amit Forlit', 'USD', false, 'Imported from CSV'),
  ('Shlomo Shamir', 'USD', false, 'Imported from CSV'),
  ('Daniel Koss', 'USD', false, 'Imported from CSV'),
  ('Nimrod Karni', 'USD', false, 'Imported from CSV'),
  ('Uri Golani', 'USD', false, 'Imported from CSV'),
  ('Yoni Leiman', 'USD', false, 'Imported from CSV'),
  ('Shimon Sheves', 'USD', false, 'Imported from CSV'),
  ('Alon Pomeranc', 'USD', false, 'Imported from CSV'),
  ('Shahar Ben Moshe', 'USD', false, 'Imported from CSV'),
  ('Boaz Palgi', 'USD', false, 'Imported from CSV'),
  ('Eitan Azta', 'USD', false, 'Imported from CSV'),
  ('Nurit Bachrach', 'USD', false, 'Imported from CSV'),
  ('Zwi Williger', 'USD', false, 'Imported from CSV'),
  ('Erez Kleinman', 'USD', false, 'Imported from CSV'),
  ('Uri Tal', 'USD', false, 'Imported from CSV'),
  ('Robert Sherbin', 'USD', false, 'Imported from CSV'),
  ('Rubin Schlussel', 'USD', false, 'Imported from CSV'),
  ('Gad Fux', 'USD', false, 'Imported from CSV'),
  ('Barak Eilam', 'USD', false, 'Imported from CSV'),
  ('Michele Maiman Firon', 'USD', false, 'Imported from CSV'),
  ('Shimon Greenberg', 'USD', false, 'Imported from CSV'),
  ('Steve Feiger', 'USD', false, 'Imported from CSV'),
  ('Klonymus Lieberman', 'USD', false, 'Imported from CSV'),
  ('Abraham Fuchs', 'USD', false, 'Imported from CSV'),
  ('Niv Zecler', 'USD', false, 'Imported from CSV'),
  ('Barak Perlman', 'USD', false, 'Imported from CSV'),
  ('Ian Fagelson', 'USD', false, 'Imported from CSV'),
  ('Daniel Levinson', 'USD', false, 'Imported from CSV'),
  ('Ilan Grinberg', 'USD', false, 'Imported from CSV'),
  ('Dror Nahumi', 'USD', false, 'Imported from CSV'),
  ('Shmuel Eden', 'USD', false, 'Imported from CSV'),
  ('Robert Weisz', 'USD', false, 'Imported from CSV'),
  ('Albert Milstein', 'USD', false, 'Imported from CSV'),
  ('Dan Tocatly', 'USD', false, 'Imported from CSV'),
  ('Alon Reshef', 'USD', false, 'Imported from CSV'),
  ('Orit Karabel', 'USD', false, 'Imported from CSV'),
  ('Alex Bernstein', 'USD', false, 'Imported from CSV'),
  ('Uri Ben Menachem', 'USD', false, 'Imported from CSV'),
  ('Shaul Rikman', 'USD', false, 'Imported from CSV'),
  ('Eran Farajun', 'USD', false, 'Imported from CSV'),
  ('Alon Even Chen', 'USD', false, 'Imported from CSV'),
  ('Sharon Hashimshoni', 'USD', false, 'Imported from CSV'),
  ('Ruli Ben Michael', 'USD', false, 'Imported from CSV'),
  ('Dana Preminger', 'USD', false, 'Imported from CSV'),
  ('Roni Atoun', 'USD', false, 'Imported from CSV'),
  ('Dov Albukrek', 'USD', false, 'Imported from CSV'),
  ('Amram Eitan', 'USD', false, 'Imported from CSV'),
  ('Kenneth Beckett', 'USD', false, 'Imported from CSV'),
  ('Idit Ziv', 'USD', false, 'Imported from CSV'),
  ('Barry Kirschenbaum', 'USD', false, 'Imported from CSV'),
  ('Hillel Chapman', 'USD', false, 'Imported from CSV'),
  ('Dotan Siman Tov', 'USD', false, 'Imported from CSV'),
  ('Lior Bahat', 'USD', false, 'Imported from CSV'),
  ('Global NET team Global NET', 'USD', false, 'Imported from CSV'),
  ('Brian Cooper', 'USD', false, 'Imported from CSV'),
  ('David Govrin', 'USD', false, 'Imported from CSV'),
  ('Rony Lerner', 'USD', false, 'Imported from CSV'),
  ('Eyal Brayer', 'USD', false, 'Imported from CSV'),
  ('Elazar Yakirevich', 'USD', false, 'Imported from CSV'),
  ('Benyamin Koren', 'USD', false, 'Imported from CSV'),
  ('Yoav Gross', 'USD', false, 'Imported from CSV'),
  ('Israel Shaked', 'USD', false, 'Imported from CSV'),
  ('Nurit Preis', 'USD', false, 'Imported from CSV'),
  ('Michael Tsukerman', 'USD', false, 'Imported from CSV'),
  ('Moshe Namdar', 'USD', false, 'Imported from CSV'),
  ('Shay Mizrachi', 'USD', false, 'Imported from CSV'),
  ('Amiram Shore', 'USD', false, 'Imported from CSV'),
  ('Frederick Fiddle', 'USD', false, 'Imported from CSV'),
  ('Gil Serok', 'USD', false, 'Imported from CSV'),
  ('Yuval Naftaly', 'USD', false, 'Imported from CSV'),
  ('Peter Gyenes', 'USD', false, 'Imported from CSV'),
  ('Inna Magazinik', 'USD', false, 'Imported from CSV'),
  ('Oded Edelman', 'USD', false, 'Imported from CSV'),
  ('Howard Loboda', 'USD', false, 'Imported from CSV'),
  ('Eli Rosenblum', 'USD', false, 'Imported from CSV'),
  ('Michael Dayan', 'USD', false, 'Imported from CSV'),
  ('Yoram Baumann', 'USD', false, 'Imported from CSV'),
  ('Jacob Sadan', 'USD', false, 'Imported from CSV'),
  ('Yariv Avrahami', 'USD', false, 'Imported from CSV'),
  ('Roee Shapiro', 'USD', false, 'Imported from CSV'),
  ('Yaniv Radia', 'USD', false, 'Imported from CSV'),
  ('Salo Mandelbaum', 'USD', false, 'Imported from CSV'),
  ('David Haramati', 'USD', false, 'Imported from CSV'),
  ('Sagi Michelson', 'USD', false, 'Imported from CSV'),
  ('Dov Lavi Bleiweiss', 'USD', false, 'Imported from CSV'),
  ('Reuben Schrift', 'USD', false, 'Imported from CSV'),
  ('Ariel Spivak', 'USD', false, 'Imported from CSV'),
  ('Oren Avraham', 'USD', false, 'Imported from CSV'),
  ('Dan Krausz', 'USD', false, 'Imported from CSV'),
  ('Maya Shaked Azulay', 'USD', false, 'Imported from CSV'),
  ('Joseph Fellus', 'USD', false, 'Imported from CSV'),
  ('Scott Spear', 'USD', false, 'Imported from CSV'),
  ('Doron Greifman', 'USD', false, 'Imported from CSV'),
  ('Ryan Rapaski', 'USD', false, 'Imported from CSV'),
  ('Yair Averbuch', 'USD', false, 'Imported from CSV'),
  ('Yigal Shefer', 'USD', false, 'Imported from CSV'),
  ('Eli Rosenberg', 'USD', false, 'Imported from CSV'),
  ('Naomi Rudich', 'USD', false, 'Imported from CSV'),
  ('Alon Ginsburg', 'USD', false, 'Imported from CSV'),
  ('Moshe Lehrer', 'USD', false, 'Imported from CSV'),
  ('Zvika Golos', 'USD', false, 'Imported from CSV'),
  ('Jacob Asia', 'USD', false, 'Imported from CSV'),
  ('Arie Rapoport', 'USD', false, 'Imported from CSV'),
  ('Yariv Robinson', 'USD', false, 'Imported from CSV'),
  ('Orna Kleinman', 'USD', false, 'Imported from CSV'),
  ('Amnon Duchovne', 'USD', false, 'Imported from CSV'),
  ('Amikam Sade', 'USD', false, 'Imported from CSV'),
  ('Chen Gaist', 'USD', false, 'Imported from CSV'),
  ('Gil Shalit', 'USD', false, 'Imported from CSV'),
  ('Brian Horner', 'USD', false, 'Imported from CSV'),
  ('David Frankel', 'USD', false, 'Imported from CSV'),
  ('Aviad Segal', 'USD', false, 'Imported from CSV'),
  ('Naftali and Dalia Narkys', 'USD', false, 'Imported from CSV'),
  ('Eran Yaniv', 'USD', false, 'Imported from CSV'),
  ('Boaz Waksman', 'USD', false, 'Imported from CSV'),
  ('Michael Winter', 'USD', false, 'Imported from CSV'),
  ('Jeffrey Herbst', 'USD', false, 'Imported from CSV'),
  ('Linda Rand', 'USD', false, 'Imported from CSV'),
  ('Sanford Bokor', 'USD', false, 'Imported from CSV'),
  ('Yaacov Kotlicki', 'USD', false, 'Imported from CSV'),
  ('Ronnen Lovinger', 'USD', false, 'Imported from CSV'),
  ('Jacob Rogovin', 'USD', false, 'Imported from CSV'),
  ('Yitzhak Mizrahi', 'USD', false, 'Imported from CSV'),
  ('Ron Senator', 'USD', false, 'Imported from CSV'),
  ('Adi Danon', 'USD', false, 'Imported from CSV'),
  ('Marc Stern', 'USD', false, 'Imported from CSV'),
  ('Edna Mandelker', 'USD', false, 'Imported from CSV'),
  ('Zachary Ball', 'USD', false, 'Imported from CSV'),
  ('Yaakov Hadar', 'USD', false, 'Imported from CSV'),
  ('Yair Ziv', 'USD', false, 'Imported from CSV'),
  ('Roie Edelman', 'USD', false, 'Imported from CSV'),
  ('David Thaler', 'USD', false, 'Imported from CSV'),
  ('Svetlana Hefetz', 'USD', false, 'Imported from CSV'),
  ('Ziv Shalev', 'USD', false, 'Imported from CSV'),
  ('Eran Inbar', 'USD', false, 'Imported from CSV'),
  ('Noa Parag', 'USD', false, 'Imported from CSV'),
  ('Shraga Shahak', 'USD', false, 'Imported from CSV'),
  ('Tal Levine Arad', 'USD', false, 'Imported from CSV'),
  ('Ilan Shemtov', 'USD', false, 'Imported from CSV'),
  ('Rakefet Kuperman', 'USD', false, 'Imported from CSV'),
  ('Prasanna Chimata', 'USD', false, 'Imported from CSV'),
  ('Joseph Ashkenazi', 'USD', false, 'Imported from CSV'),
  ('Yoram Duchovne', 'USD', false, 'Imported from CSV'),
  ('Alexandra Barth', 'USD', false, 'Imported from CSV'),
  ('Susan Zechter', 'USD', false, 'Imported from CSV'),
  ('Samuel Sattath', 'USD', false, 'Imported from CSV'),
  ('Michal Vermus', 'USD', false, 'Imported from CSV'),
  ('Maris Rosenberg', 'USD', false, 'Imported from CSV'),
  ('Elad Ichai', 'USD', false, 'Imported from CSV'),
  ('Avraham Marchavka', 'USD', false, 'Imported from CSV'),
  ('Shraga Michelson', 'USD', false, 'Imported from CSV'),
  ('Sami Shiro', 'USD', false, 'Imported from CSV'),
  ('Stan Weissbrot', 'USD', false, 'Imported from CSV'),
  ('Rafael Ashkenazi', 'USD', false, 'Imported from CSV'),
  ('Gal Ehrlich', 'USD', false, 'Imported from CSV'),
  ('Ilan Orenstein', 'USD', false, 'Imported from CSV'),
  ('Yahal Zilka', 'USD', false, 'Imported from CSV'),
  ('William Creekmore', 'USD', false, 'Imported from CSV'),
  ('Eti Livni', 'USD', false, 'Imported from CSV'),
  ('Meir Mania', 'USD', false, 'Imported from CSV'),
  ('Yael Achiaz', 'USD', false, 'Imported from CSV'),
  ('Dror Goldenberg', 'USD', false, 'Imported from CSV'),
  ('Orren Peled', 'USD', false, 'Imported from CSV'),
  ('Shay Geler', 'USD', false, 'Imported from CSV'),
  ('Suzana Kugler', 'USD', false, 'Imported from CSV'),
  ('Galila Oren', 'USD', false, 'Imported from CSV'),
  ('Chaim Zach', 'USD', false, 'Imported from CSV'),
  ('Mor Atlas', 'USD', false, 'Imported from CSV'),
  ('Sophie Landau', 'USD', false, 'Imported from CSV'),
  ('Lihi Tadmor', 'USD', false, 'Imported from CSV'),
  ('Amir Maoz', 'USD', false, 'Imported from CSV'),
  ('Eyal Chomski', 'USD', false, 'Imported from CSV'),
  ('Danit Levi', 'USD', false, 'Imported from CSV'),
  ('Asher Grinbaum', 'USD', false, 'Imported from CSV'),
  ('Gilly Yohanani', 'USD', false, 'Imported from CSV'),
  ('Yoav Lachover', 'USD', false, 'Imported from CSV'),
  ('David Goren', 'USD', false, 'Imported from CSV'),
  ('Shai Beilis', 'USD', false, 'Imported from CSV'),
  ('Boaz Dinte', 'USD', false, 'Imported from CSV'),
  ('Shlomith Yaron', 'USD', false, 'Imported from CSV'),
  ('Andrew Tanzer', 'USD', false, 'Imported from CSV'),
  ('Praveen Dukkipati', 'USD', false, 'Imported from CSV'),
  ('Eli Azoulay', 'USD', false, 'Imported from CSV'),
  ('Ehud Arad', 'USD', false, 'Imported from CSV'),
  ('Gabriel Asido', 'USD', false, 'Imported from CSV'),
  ('Tlalit Prescher', 'USD', false, 'Imported from CSV'),
  ('Ifat Ginsburg', 'USD', false, 'Imported from CSV'),
  ('Snir Hassin', 'USD', false, 'Imported from CSV'),
  ('Menahem Waingarten', 'USD', false, 'Imported from CSV'),
  ('Tomer Wertheimer', 'USD', false, 'Imported from CSV'),
  ('David Yahav', 'USD', false, 'Imported from CSV'),
  ('Danny Gez', 'USD', false, 'Imported from CSV'),
  ('David Goone', 'USD', false, 'Imported from CSV'),
  ('Gal Dagan', 'USD', false, 'Imported from CSV'),
  ('Daniel Slivkin', 'USD', false, 'Imported from CSV'),
  ('Daniel Krivelevich', 'USD', false, 'Imported from CSV'),
  ('Alon Grinker', 'USD', false, 'Imported from CSV'),
  ('Tamar Mozes Borovitz', 'USD', false, 'Imported from CSV'),
  ('Mordechay Maaravi', 'USD', false, 'Imported from CSV'),
  ('Joshua Levinberg', 'USD', false, 'Imported from CSV'),
  ('Yitshak Ben', 'USD', false, 'Imported from CSV'),
  ('Guy Hadar', 'USD', false, 'Imported from CSV'),
  ('Yoram Avi', 'USD', false, 'Imported from CSV'),
  ('Michael Pougach', 'USD', false, 'Imported from CSV'),
  ('Tomer Dor', 'USD', false, 'Imported from CSV'),
  ('Noam Zegman', 'USD', false, 'Imported from CSV'),
  ('Yoram Mizrachi', 'USD', false, 'Imported from CSV'),
  ('Roni Tuttnauer', 'USD', false, 'Imported from CSV'),
  ('Gil Raveh', 'USD', false, 'Imported from CSV'),
  ('Yonatan Stern', 'USD', false, 'Imported from CSV'),
  ('Yair Koren', 'USD', false, 'Imported from CSV'),
  ('Nahman Yahav', 'USD', false, 'Imported from CSV'),
  ('Yair Tzur', 'USD', false, 'Imported from CSV'),
  ('Roni Stadler', 'USD', false, 'Imported from CSV'),
  ('Ross Chaifetz', 'USD', false, 'Imported from CSV'),
  ('Shmuel Carmon', 'USD', false, 'Imported from CSV'),
  ('Rony Eitany', 'USD', false, 'Imported from CSV'),
  ('Daniel Slimak', 'USD', false, 'Imported from CSV'),
  ('Gadi Gerbi', 'USD', false, 'Imported from CSV'),
  ('Haim Rosenbaum', 'USD', false, 'Imported from CSV'),
  ('Zvi Greenstein', 'USD', false, 'Imported from CSV'),
  ('Amit Gatenyo', 'USD', false, 'Imported from CSV'),
  ('Aline Ajami Atzmon', 'USD', false, 'Imported from CSV'),
  ('Liat Oron', 'USD', false, 'Imported from CSV'),
  ('Gavriel Taub', 'USD', false, 'Imported from CSV'),
  ('Aya Shahar', 'USD', false, 'Imported from CSV'),
  ('Moshe Friedman', 'USD', false, 'Imported from CSV'),
  ('Guy Ben', 'USD', false, 'Imported from CSV'),
  ('Rafi Albo', 'USD', false, 'Imported from CSV'),
  ('Iftach Shlomi', 'USD', false, 'Imported from CSV'),
  ('Adina Greenberg', 'USD', false, 'Imported from CSV'),
  ('Abraham Stern', 'USD', false, 'Imported from CSV'),
  ('Vicky Levy', 'USD', false, 'Imported from CSV'),
  ('Matatya Schechtman', 'USD', false, 'Imported from CSV'),
  ('Moti Hamama', 'USD', false, 'Imported from CSV'),
  ('Shay Onn', 'USD', false, 'Imported from CSV'),
  ('Ronen Matry', 'USD', false, 'Imported from CSV'),
  ('Orit Shamir', 'USD', false, 'Imported from CSV'),
  ('Dan Kampel', 'USD', false, 'Imported from CSV'),
  ('Guy Assif', 'USD', false, 'Imported from CSV'),
  ('Nir Avni', 'USD', false, 'Imported from CSV'),
  ('Ran Achituv', 'USD', false, 'Imported from CSV'),
  ('Ayal Brenner', 'USD', false, 'Imported from CSV'),
  ('Shulamit Shimon', 'USD', false, 'Imported from CSV'),
  ('Shameem Kahn', 'USD', false, 'Imported from CSV'),
  ('Herman Zell', 'USD', false, 'Imported from CSV'),
  ('Jerry Holtz', 'USD', false, 'Imported from CSV'),
  ('Emil Vainshel', 'USD', false, 'Imported from CSV'),
  ('Yaron Itay', 'USD', false, 'Imported from CSV'),
  ('Yuval Bar', 'USD', false, 'Imported from CSV'),
  ('Baruch Morag', 'USD', false, 'Imported from CSV'),
  ('Avi Shaked', 'USD', false, 'Imported from CSV'),
  ('Benjamin Czarny', 'USD', false, 'Imported from CSV'),
  ('Tal Berger', 'USD', false, 'Imported from CSV'),
  ('Baruch Tratner', 'USD', false, 'Imported from CSV'),
  ('Amnon Pardo', 'USD', false, 'Imported from CSV'),
  ('Orr Barak', 'USD', false, 'Imported from CSV'),
  ('Barak Naveh', 'USD', false, 'Imported from CSV'),
  ('Ariel Gordon', 'USD', false, 'Imported from CSV'),
  ('Sammy Shukrun', 'USD', false, 'Imported from CSV'),
  ('Ofir Rimoni', 'USD', false, 'Imported from CSV'),
  ('Avrum Weinfeld', 'USD', false, 'Imported from CSV'),
  ('Yigal Shemesh', 'USD', false, 'Imported from CSV'),
  ('Uri Efroni', 'USD', false, 'Imported from CSV'),
  ('Ben Fruchter', 'USD', false, 'Imported from CSV'),
  ('Ivan Ferrer', 'USD', false, 'Imported from CSV'),
  ('Doron Sharabany', 'USD', false, 'Imported from CSV'),
  ('Ronen Barel', 'USD', false, 'Imported from CSV'),
  ('David Schreiber', 'USD', false, 'Imported from CSV'),
  ('Lior Suchard', 'USD', false, 'Imported from CSV'),
  ('Daniel Halpern', 'USD', false, 'Imported from CSV'),
  ('Mina Beilis', 'USD', false, 'Imported from CSV'),
  ('Ygal Zror', 'USD', false, 'Imported from CSV'),
  ('Ronen Tavor', 'USD', false, 'Imported from CSV'),
  ('Miriyam Kerbs', 'USD', false, 'Imported from CSV'),
  ('Erez Ben Ezra', 'USD', false, 'Imported from CSV'),
  ('Talya Ben Tovim', 'USD', false, 'Imported from CSV'),
  ('Yoav Holzer', 'USD', false, 'Imported from CSV'),
  ('Doron Shamir', 'USD', false, 'Imported from CSV'),
  ('Benny Glam', 'USD', false, 'Imported from CSV'),
  ('Ziv Carthy', 'USD', false, 'Imported from CSV'),
  ('Ron Schulman', 'USD', false, 'Imported from CSV'),
  ('Idan Nizri', 'USD', false, 'Imported from CSV'),
  ('Dominic Sergi', 'USD', false, 'Imported from CSV'),
  ('Uri Levine', 'USD', false, 'Imported from CSV'),
  ('Gabby Rubin', 'USD', false, 'Imported from CSV'),
  ('Eran Borovik', 'USD', false, 'Imported from CSV'),
  ('Shy Avni', 'USD', false, 'Imported from CSV'),
  ('Rami Romano', 'USD', false, 'Imported from CSV'),
  ('David Sitten', 'USD', false, 'Imported from CSV'),
  ('Oren Buskila', 'USD', false, 'Imported from CSV'),
  ('Tomer Tzuman', 'USD', false, 'Imported from CSV'),
  ('Roee Schreiber', 'USD', false, 'Imported from CSV'),
  ('Lior Yaffe Cohen', 'USD', false, 'Imported from CSV'),
  ('Ehud Elizur', 'USD', false, 'Imported from CSV'),
  ('Avi Blumenfeld', 'USD', false, 'Imported from CSV'),
  ('Charles Serlin', 'USD', false, 'Imported from CSV'),
  ('Edna Rabina Wilamowski', 'USD', false, 'Imported from CSV'),
  ('Ronen Ben Ami', 'USD', false, 'Imported from CSV'),
  ('Yaniv Perry', 'USD', false, 'Imported from CSV'),
  ('Uri Pundak', 'USD', false, 'Imported from CSV'),
  ('Eyal Itzhak Cohen', 'USD', false, 'Imported from CSV'),
  ('Efraim Cohen', 'USD', false, 'Imported from CSV'),
  ('Ruth Shafir', 'USD', false, 'Imported from CSV'),
  ('Amram Golan', 'USD', false, 'Imported from CSV'),
  ('Bar Stein', 'USD', false, 'Imported from CSV'),
  ('Guy Greenberg', 'USD', false, 'Imported from CSV'),
  ('David Waimann', 'USD', false, 'Imported from CSV'),
  ('Daniel Johananoff', 'USD', false, 'Imported from CSV'),
  ('Amit Levine', 'USD', false, 'Imported from CSV'),
  ('Moti Lichi', 'USD', false, 'Imported from CSV'),
  ('Zvi Shmueli', 'USD', false, 'Imported from CSV'),
  ('Salvador Huino', 'USD', false, 'Imported from CSV'),
  ('Dan Pasternak', 'USD', false, 'Imported from CSV'),
  ('Oren Rosenzweig', 'USD', false, 'Imported from CSV'),
  ('Nir Chanoch', 'USD', false, 'Imported from CSV'),
  ('Moshe Barnes', 'USD', false, 'Imported from CSV'),
  ('Moshe Matityahu', 'USD', false, 'Imported from CSV'),
  ('Maya Eldar', 'USD', false, 'Imported from CSV'),
  ('Shalom Avni', 'USD', false, 'Imported from CSV'),
  ('Benny Porat', 'USD', false, 'Imported from CSV'),
  ('Sasha Slimak', 'USD', false, 'Imported from CSV'),
  ('Tamir Mizrahi', 'USD', false, 'Imported from CSV'),
  ('Barry Shaked', 'USD', false, 'Imported from CSV'),
  ('Ya''aqov Segal', 'USD', false, 'Imported from CSV'),
  ('Yosef Ben Dor', 'USD', false, 'Imported from CSV'),
  ('Zivit Beilis', 'USD', false, 'Imported from CSV'),
  ('Meir Dalumi', 'USD', false, 'Imported from CSV'),
  ('Yoram Tietz', 'USD', false, 'Imported from CSV'),
  ('Yam Rubinstein', 'USD', false, 'Imported from CSV'),
  ('Rotem Barzilay', 'USD', false, 'Imported from CSV'),
  ('Yoav Narkys', 'USD', false, 'Imported from CSV'),
  ('Uri Zror', 'USD', false, 'Imported from CSV'),
  ('Zohar Gafni', 'USD', false, 'Imported from CSV'),
  ('Zvi Cohen', 'USD', false, 'Imported from CSV'),
  ('Michael Ashkenazi', 'USD', false, 'Imported from CSV'),
  ('Yossi Reznik', 'USD', false, 'Imported from CSV'),
  ('Yossef Semeloy', 'USD', false, 'Imported from CSV'),
  ('Eliezer Piha', 'USD', false, 'Imported from CSV'),
  ('Rev Lebardedian', 'USD', false, 'Imported from CSV'),
  ('Boaz Paz', 'USD', false, 'Imported from CSV'),
  ('Sarah Levi', 'USD', false, 'Imported from CSV'),
  ('Nicolas Gortzounian', 'USD', false, 'Imported from CSV'),
  ('Orit Sinai', 'USD', false, 'Imported from CSV'),
  ('Aron Ezra', 'USD', false, 'Imported from CSV'),
  ('Abraham Raz', 'USD', false, 'Imported from CSV'),
  ('Itai Forlit', 'USD', false, 'Imported from CSV'),
  ('Assaf Feldman', 'USD', false, 'Imported from CSV'),
  ('Israel and Yael David', 'USD', false, 'Imported from CSV'),
  ('Elad Raz', 'USD', false, 'Imported from CSV'),
  ('Brent Gindel', 'USD', false, 'Imported from CSV'),
  ('Zeev Livnat', 'USD', false, 'Imported from CSV'),
  ('Bradley Rosenblatt', 'USD', false, 'Imported from CSV'),
  ('Doron Alter', 'USD', false, 'Imported from CSV'),
  ('Dael Shalev', 'USD', false, 'Imported from CSV'),
  ('Dan Wartski', 'USD', false, 'Imported from CSV'),
  ('Eliezer Horovitz', 'USD', false, 'Imported from CSV'),
  ('Ofer Ben', 'USD', false, 'Imported from CSV'),
  ('Or Kleinman', 'USD', false, 'Imported from CSV'),
  ('Ovadya Hamama', 'USD', false, 'Imported from CSV'),
  ('Orna Tuval', 'USD', false, 'Imported from CSV'),
  ('Alon Lev Hertz', 'USD', false, 'Imported from CSV'),
  ('Dan Shefer', 'USD', false, 'Imported from CSV'),
  ('Noa Grinberg', 'USD', false, 'Imported from CSV'),
  ('Ari Hillel', 'USD', false, 'Imported from CSV'),
  ('Tomer Bogin', 'USD', false, 'Imported from CSV'),
  ('Lion Bassat', 'USD', false, 'Imported from CSV'),
  ('Yotam Elal', 'USD', false, 'Imported from CSV'),
  ('Amos and Lilach Ben', 'USD', false, 'Imported from CSV'),
  ('Erez Rosenwaks', 'USD', false, 'Imported from CSV'),
  ('Aviram Gutman', 'USD', false, 'Imported from CSV'),
  ('Carofini Segal', 'USD', false, 'Imported from CSV'),
  ('Omer Avlas', 'USD', false, 'Imported from CSV'),
  ('Keryn Schreiber', 'USD', false, 'Imported from CSV'),
  ('Shay Dayan', 'USD', false, 'Imported from CSV'),
  ('Shlomo Wertheim', 'USD', false, 'Imported from CSV'),
  ('Oded Kopatz', 'USD', false, 'Imported from CSV'),
  ('Ori Druker', 'USD', false, 'Imported from CSV'),
  ('Amichai Steimberg', 'USD', false, 'Imported from CSV'),
  ('Amit Zeevi', 'USD', false, 'Imported from CSV'),
  ('Matthew Rubin', 'USD', false, 'Imported from CSV'),
  ('Sagi Rotem', 'USD', false, 'Imported from CSV'),
  ('Gabriel Schechtman', 'USD', false, 'Imported from CSV'),
  ('Neil Corney', 'USD', false, 'Imported from CSV'),
  ('Michael Danaher', 'USD', false, 'Imported from CSV'),
  ('Jared Holzman', 'USD', false, 'Imported from CSV'),
  ('Mordechay Baitner', 'USD', false, 'Imported from CSV'),
  ('Nhevo Kaufman', 'USD', false, 'Imported from CSV'),
  ('Miriam Micky Tuttnauer', 'USD', false, 'Imported from CSV'),
  ('Viki Bencuya Sagol', 'USD', false, 'Imported from CSV'),
  ('Amit Katz', 'USD', false, 'Imported from CSV'),
  ('Nitzan Shapira', 'USD', false, 'Imported from CSV'),
  ('Nurith Jaglom', 'USD', false, 'Imported from CSV'),
  ('Nir Tzur', 'USD', false, 'Imported from CSV'),
  ('Adina Shorr', 'USD', false, 'Imported from CSV'),
  ('Yehoshua Zifrut', 'USD', false, 'Imported from CSV'),
  ('Mordechai Nimrod Gindi', 'USD', false, 'Imported from CSV'),
  ('Gil Hassin', 'USD', false, 'Imported from CSV'),
  ('Peter Bermont', 'USD', false, 'Imported from CSV'),
  ('Ishay Yaari', 'USD', false, 'Imported from CSV'),
  ('Eviatar Cohen Hav', 'USD', false, 'Imported from CSV'),
  ('Haim Helman', 'USD', false, 'Imported from CSV'),
  ('Amit Berger', 'USD', false, 'Imported from CSV'),
  ('Adrian Bailey', 'USD', false, 'Imported from CSV'),
  ('Ohad Freund', 'USD', false, 'Imported from CSV'),
  ('Aaron Shenhar', 'USD', false, 'Imported from CSV'),
  ('Ran Oz', 'USD', false, 'Imported from CSV'),
  ('Richard Kaitz', 'USD', false, 'Imported from CSV'),
  ('Efraeim Cohen', 'USD', false, 'Imported from CSV'),
  ('Beatriz Levi', 'USD', false, 'Imported from CSV'),
  ('Noam Wolf', 'USD', false, 'Imported from CSV'),
  ('Haim Marcovitz', 'USD', false, 'Imported from CSV'),
  ('Eyal Pais', 'USD', false, 'Imported from CSV'),
  ('Itzhak Zarnitzky', 'USD', false, 'Imported from CSV'),
  ('Avi Gelman', 'USD', false, 'Imported from CSV'),
  ('Mika Azia', 'USD', false, 'Imported from CSV'),
  ('Amier Levkowitz', 'USD', false, 'Imported from CSV'),
  ('Mendi Rosencrantz', 'USD', false, 'Imported from CSV'),
  ('Udi Goren', 'USD', false, 'Imported from CSV'),
  ('Lior Baraf', 'USD', false, 'Imported from CSV'),
  ('Michael Lustig', 'USD', false, 'Imported from CSV'),
  ('Rami Pais', 'USD', false, 'Imported from CSV'),
  ('Nissim Gvili', 'USD', false, 'Imported from CSV'),
  ('Omri Gur Lavie', 'USD', false, 'Imported from CSV'),
  ('Sima Ben Chetrit', 'USD', false, 'Imported from CSV'),
  ('Yuval Katz', 'USD', false, 'Imported from CSV'),
  ('Dan Stemmer', 'USD', false, 'Imported from CSV'),
  ('Netanela Kristal', 'USD', false, 'Imported from CSV'),
  ('Maya Landau', 'USD', false, 'Imported from CSV'),
  ('David Chairman', 'USD', false, 'Imported from CSV'),
  ('Ruth Siegel', 'USD', false, 'Imported from CSV'),
  ('Izaac Weitz', 'USD', false, 'Imported from CSV'),
  ('Erez Nossek', 'USD', false, 'Imported from CSV'),
  ('Uziel Waissman', 'USD', false, 'Imported from CSV'),
  ('Asaf Arieli', 'USD', false, 'Imported from CSV'),
  ('Yuval Keren', 'USD', false, 'Imported from CSV'),
  ('Patricia Margulies', 'USD', false, 'Imported from CSV'),
  ('Ran Ribenzaft', 'USD', false, 'Imported from CSV'),
  ('Lenny Recanati', 'USD', false, 'Imported from CSV'),
  ('Lital Slavin', 'USD', false, 'Imported from CSV'),
  ('Issachar Gerlitz', 'USD', false, 'Imported from CSV'),
  ('Steven Greenbaum', 'USD', false, 'Imported from CSV'),
  ('Eran Fuchs', 'USD', false, 'Imported from CSV'),
  ('Ron Eyal', 'USD', false, 'Imported from CSV'),
  ('Eyal Shemesh', 'USD', false, 'Imported from CSV'),
  ('Susan Wagner', 'USD', false, 'Imported from CSV'),
  ('Itai Yenon', 'USD', false, 'Imported from CSV'),
  ('Eyal Cohen', 'USD', false, 'Imported from CSV'),
  ('Joseph Kopatch', 'USD', false, 'Imported from CSV'),
  ('Ilan Swirsky', 'USD', false, 'Imported from CSV'),
  ('Ehud Hameiri', 'USD', false, 'Imported from CSV'),
  ('Oren Shefler', 'USD', false, 'Imported from CSV'),
  ('Gila Waimann', 'USD', false, 'Imported from CSV'),
  ('Arnon Carmel', 'USD', false, 'Imported from CSV'),
  ('Brian Nebel', 'USD', false, 'Imported from CSV'),
  ('Avi Goren', 'USD', false, 'Imported from CSV'),
  ('Adam Gotskind', 'USD', false, 'Imported from CSV'),
  ('Moshe Nerson', 'USD', false, 'Imported from CSV'),
  ('Shlomo Jeret', 'USD', false, 'Imported from CSV'),
  ('Shimon Keren', 'USD', false, 'Imported from CSV'),
  ('Yehezkel Gabai', 'USD', false, 'Imported from CSV'),
  ('Yevgeny Kliteynik', 'USD', false, 'Imported from CSV'),
  ('Eyal Sheratzky', 'USD', false, 'Imported from CSV'),
  ('Meir Zohar', 'USD', false, 'Imported from CSV'),
  ('Hana Ron', 'USD', false, 'Imported from CSV'),
  ('Ran Ravid', 'USD', false, 'Imported from CSV'),
  ('David Baron', 'USD', false, 'Imported from CSV'),
  ('Yehoshua Sarig', 'USD', false, 'Imported from CSV'),
  ('Eyal Fruchter', 'USD', false, 'Imported from CSV'),
  ('Uriel Fischer', 'USD', false, 'Imported from CSV'),
  ('Yoram Hadar', 'USD', false, 'Imported from CSV'),
  ('Ran Kampel', 'USD', false, 'Imported from CSV'),
  ('Albert Saplitski', 'USD', false, 'Imported from CSV'),
  ('Yonatan Malkiman', 'USD', false, 'Imported from CSV'),
  ('Oren Hadar', 'USD', false, 'Imported from CSV'),
  ('Eric Sirkin', 'USD', false, 'Imported from CSV'),
  ('Shahar Erez', 'USD', false, 'Imported from CSV'),
  ('Shalom Madar', 'USD', false, 'Imported from CSV'),
  ('James Schultz', 'USD', false, 'Imported from CSV'),
  ('Scott Lawrence', 'USD', false, 'Imported from CSV'),
  ('Dore Friedman', 'USD', false, 'Imported from CSV'),
  ('Ofer Levy', 'USD', false, 'Imported from CSV'),
  ('Louis Blumberg', 'USD', false, 'Imported from CSV'),
  ('Gil Hecht', 'USD', false, 'Imported from CSV'),
  ('Jeffrey Knopping', 'USD', false, 'Imported from CSV'),
  ('Marit Slavin', 'USD', false, 'Imported from CSV'),
  ('Marc Strongin', 'USD', false, 'Imported from CSV'),
  ('Lilach Shaya', 'USD', false, 'Imported from CSV'),
  ('Niv Kagan', 'USD', false, 'Imported from CSV'),
  ('Liad Orr', 'USD', false, 'Imported from CSV'),
  ('Thomas Latsos', 'USD', false, 'Imported from CSV'),
  ('Octavian Patrascu', 'USD', false, 'Imported from CSV'),
  ('Shmuel Herman', 'USD', false, 'Imported from CSV'),
  ('Avraham Engel', 'USD', false, 'Imported from CSV'),
  ('Israel Meilik', 'USD', false, 'Imported from CSV'),
  ('Eyal Levin', 'USD', false, 'Imported from CSV'),
  ('Shahaf Shuler', 'USD', false, 'Imported from CSV'),
  ('Dotan Klein', 'USD', false, 'Imported from CSV'),
  ('David Fish', 'USD', false, 'Imported from CSV'),
  ('Oren Shamir', 'USD', false, 'Imported from CSV'),
  ('Phinhas and Sara Dickstein', 'USD', false, 'Imported from CSV'),
  ('Nomi Kapalner', 'USD', false, 'Imported from CSV'),
  ('Ofer Eldar', 'USD', false, 'Imported from CSV'),
  ('Tomer Weissman', 'USD', false, 'Imported from CSV'),
  ('Adi Zamir', 'USD', false, 'Imported from CSV'),
  ('Roi Ben Itzhak', 'USD', false, 'Imported from CSV'),
  ('Amit Goren', 'USD', false, 'Imported from CSV'),
  ('Erez Shaham', 'USD', false, 'Imported from CSV'),
  ('Elan Margulies', 'USD', false, 'Imported from CSV'),
  ('Shani Shalgi', 'USD', false, 'Imported from CSV'),
  ('Idan Geva', 'USD', false, 'Imported from CSV'),
  ('Yosef Cohen', 'USD', false, 'Imported from CSV'),
  ('Jack Faintuch', 'USD', false, 'Imported from CSV'),
  ('Mary Beth Gaspich', 'USD', false, 'Imported from CSV'),
  ('Daniel Slutzky', 'USD', false, 'Imported from CSV'),
  ('Efraim Lavie', 'USD', false, 'Imported from CSV'),
  ('Tehila Ben Moshe', 'USD', false, 'Imported from CSV'),
  ('Michael Barnatan', 'USD', false, 'Imported from CSV'),
  ('Joseph Unterman', 'USD', false, 'Imported from CSV'),
  ('Guy Avtalion', 'USD', false, 'Imported from CSV'),
  ('Sharon Kotlicki', 'USD', false, 'Imported from CSV'),
  ('Yehuda Tendler', 'USD', false, 'Imported from CSV'),
  ('Alon Piltz', 'USD', false, 'Imported from CSV'),
  ('Eran Maoz', 'USD', false, 'Imported from CSV'),
  ('Yaron Lamy', 'USD', false, 'Imported from CSV'),
  ('Fabian Tenenbaum', 'USD', false, 'Imported from CSV'),
  ('Dalia Johananoff', 'USD', false, 'Imported from CSV'),
  ('Ori Peled', 'USD', false, 'Imported from CSV'),
  ('Doron Ben Eliezer', 'USD', false, 'Imported from CSV'),
  ('Michael Ishai', 'USD', false, 'Imported from CSV'),
  ('Keren Fruchtman', 'USD', false, 'Imported from CSV'),
  ('Alexander Drabkin', 'USD', false, 'Imported from CSV'),
  ('Yair Navot', 'USD', false, 'Imported from CSV'),
  ('Tamar Oz', 'USD', false, 'Imported from CSV'),
  ('Ester Hovev', 'USD', false, 'Imported from CSV'),
  ('Fred Margulies', 'USD', false, 'Imported from CSV'),
  ('Ziv Paz', 'USD', false, 'Imported from CSV'),
  ('Aviva Doron', 'USD', false, 'Imported from CSV'),
  ('Pinhas Koren', 'USD', false, 'Imported from CSV'),
  ('Michal Gonen', 'USD', false, 'Imported from CSV'),
  ('Shirley Slimak Ratner', 'USD', false, 'Imported from CSV'),
  ('Moshe Salem', 'USD', false, 'Imported from CSV'),
  ('Joseph Cohen', 'USD', false, 'Imported from CSV'),
  ('Yaniv Gruenwald', 'USD', false, 'Imported from CSV'),
  ('Moshe Reuveni', 'USD', false, 'Imported from CSV'),
  ('Natan Eitan Toledo', 'USD', false, 'Imported from CSV'),
  ('Ori Inbar', 'USD', false, 'Imported from CSV'),
  ('Rami Livnat', 'USD', false, 'Imported from CSV'),
  ('Hagay Alter', 'USD', false, 'Imported from CSV'),
  ('Tal Koren', 'USD', false, 'Imported from CSV'),
  ('Guy Piekarz', 'USD', false, 'Imported from CSV'),
  ('Gil Rubinstein', 'USD', false, 'Imported from CSV'),
  ('Noga Karni', 'USD', false, 'Imported from CSV'),
  ('Itay Azia', 'USD', false, 'Imported from CSV'),
  ('Lea Golan', 'USD', false, 'Imported from CSV'),
  ('Nicky Stup', 'USD', false, 'Imported from CSV'),
  ('Dana Ben', 'USD', false, 'Imported from CSV'),
  ('Elior Sorek', 'USD', false, 'Imported from CSV'),
  ('Alan Wise', 'USD', false, 'Imported from CSV'),
  ('Shlomit Rozenfeld', 'USD', false, 'Imported from CSV'),
  ('Joseph Brandman', 'USD', false, 'Imported from CSV'),
  ('Shmuel Yaakobi', 'USD', false, 'Imported from CSV'),
  ('Jonathan Zabusky', 'USD', false, 'Imported from CSV'),
  ('David Sherbin', 'USD', false, 'Imported from CSV'),
  ('Yaniv Kleinman', 'USD', false, 'Imported from CSV'),
  ('Robert Ciaruffoli, III', 'USD', false, 'Imported from CSV'),
  ('Michael Shay', 'USD', false, 'Imported from CSV'),
  ('Assa Zohar', 'USD', false, 'Imported from CSV'),
  ('Yoni Aziz', 'USD', false, 'Imported from CSV'),
  ('Ilan Shiloah', 'USD', false, 'Imported from CSV'),
  ('Arianna Shapira', 'USD', false, 'Imported from CSV'),
  ('Ariel Levanon', 'USD', false, 'Imported from CSV'),
  ('Naor Levi', 'USD', false, 'Imported from CSV'),
  ('Dov Gal', 'USD', false, 'Imported from CSV'),
  ('Yaniv Saylan', 'USD', false, 'Imported from CSV'),
  ('Alon Buch', 'USD', false, 'Imported from CSV'),
  ('Luv Mirani', 'USD', false, 'Imported from CSV'),
  ('Yaacov Ben Eliezer', 'USD', false, 'Imported from CSV'),
  ('Naomi Belfer', 'USD', false, 'Imported from CSV'),
  ('Alex Gurevich', 'USD', false, 'Imported from CSV'),
  ('Limor Sagiv', 'USD', false, 'Imported from CSV'),
  ('Eyal Ben Eliezer', 'USD', false, 'Imported from CSV'),
  ('Omer Peleg', 'USD', false, 'Imported from CSV'),
  ('Amiram Levinberg', 'USD', false, 'Imported from CSV'),
  ('Dror Zetouni', 'USD', false, 'Imported from CSV'),
  ('Tamar Schifter', 'USD', false, 'Imported from CSV'),
  ('Alon Haramati', 'USD', false, 'Imported from CSV'),
  ('Nir Nof', 'USD', false, 'Imported from CSV'),
  ('Rimona Flint', 'USD', false, 'Imported from CSV'),
  ('Yakar Sidis', 'USD', false, 'Imported from CSV'),
  ('Jacov Ruthstein', 'USD', false, 'Imported from CSV'),
  ('Iris Reitzes Kellerman', 'USD', false, 'Imported from CSV'),
  ('Tal Aviv', 'USD', false, 'Imported from CSV'),
  ('Lotan Morad', 'USD', false, 'Imported from CSV'),
  ('Ehud Svirsky', 'USD', false, 'Imported from CSV'),
  ('Bo Brown', 'USD', false, 'Imported from CSV'),
  ('Ran Ben', 'USD', false, 'Imported from CSV'),
  ('Kfir Matalon', 'USD', false, 'Imported from CSV'),
  ('Nir Cohen', 'USD', false, 'Imported from CSV'),
  ('Yaron Aloni', 'USD', false, 'Imported from CSV'),
  ('Gidi Raff', 'USD', false, 'Imported from CSV'),
  ('Gil Ben Hur', 'USD', false, 'Imported from CSV'),
  ('Eyal Dagan', 'USD', false, 'Imported from CSV'),
  ('Miguel Zamarripa', 'USD', false, 'Imported from CSV'),
  ('Ariel Halperin', 'USD', false, 'Imported from CSV'),
  ('Gregory Swords', 'USD', false, 'Imported from CSV'),
  ('Julien Barbier', 'USD', false, 'Imported from CSV'),
  ('Haim Giladi', 'USD', false, 'Imported from CSV'),
  ('David Ehrenberg', 'USD', false, 'Imported from CSV'),
  ('Haya Shahak', 'USD', false, 'Imported from CSV'),
  ('Yael Goren', 'USD', false, 'Imported from CSV'),
  ('Todd Stern', 'USD', false, 'Imported from CSV'),
  ('Eitan Shlisselberg', 'USD', false, 'Imported from CSV'),
  ('Avraam Fried', 'USD', false, 'Imported from CSV'),
  ('Ehud Even', 'USD', false, 'Imported from CSV'),
  ('Eldad Firon', 'USD', false, 'Imported from CSV'),
  ('Karen Levine', 'USD', false, 'Imported from CSV'),
  ('Haggit Levy', 'USD', false, 'Imported from CSV'),
  ('Gal Dalal', 'USD', false, 'Imported from CSV'),
  ('Daniel Baranes', 'USD', false, 'Imported from CSV'),
  ('Kelvin Ninh', 'USD', false, 'Imported from CSV'),
  ('Gil Slavin', 'USD', false, 'Imported from CSV'),
  ('Ari Milstein', 'USD', false, 'Imported from CSV'),
  ('Dana Landau', 'USD', false, 'Imported from CSV'),
  ('Tim Ferguson', 'USD', false, 'Imported from CSV'),
  ('Ofer Tirosh', 'USD', false, 'Imported from CSV'),
  ('Osnat Levi', 'USD', false, 'Imported from CSV'),
  ('Amos Bar Shalev', 'USD', false, 'Imported from CSV'),
  ('Omer Schalit', 'USD', false, 'Imported from CSV'),
  ('Nimrod Dassa', 'USD', false, 'Imported from CSV'),
  ('Elimelech Rosner', 'USD', false, 'Imported from CSV'),
  ('Sagiv Stavinsky', 'USD', false, 'Imported from CSV'),
  ('Zvi Bar', 'USD', false, 'Imported from CSV'),
  ('Michal Glinert', 'USD', false, 'Imported from CSV'),
  ('Dror Itzhaki', 'USD', false, 'Imported from CSV'),
  ('Amir Naiberg', 'USD', false, 'Imported from CSV'),
  ('Chava Ram', 'USD', false, 'Imported from CSV'),
  ('Keren Ungar', 'USD', false, 'Imported from CSV'),
  ('Andrew Gundle', 'USD', false, 'Imported from CSV'),
  ('Noam Goldstein', 'USD', false, 'Imported from CSV'),
  ('Tom Azar', 'USD', false, 'Imported from CSV'),
  ('Remez Bariach', 'USD', false, 'Imported from CSV'),
  ('Danny Burakov', 'USD', false, 'Imported from CSV'),
  ('Hanna Dresner Berenbaum', 'USD', false, 'Imported from CSV'),
  ('Yaki Razmovich', 'USD', false, 'Imported from CSV'),
  ('Valeria Tsukerman', 'USD', false, 'Imported from CSV'),
  ('Yoram Hoffman', 'USD', false, 'Imported from CSV'),
  ('Einav Bejerano Falah', 'USD', false, 'Imported from CSV'),
  ('Yehiel Ben Ari', 'USD', false, 'Imported from CSV'),
  ('Alon Eliakim', 'USD', false, 'Imported from CSV'),
  ('Yael Segal', 'USD', false, 'Imported from CSV'),
  ('Ronen and Pessia Katan', 'USD', false, 'Imported from CSV'),
  ('Ravit Yanko Arzi', 'USD', false, 'Imported from CSV'),
  ('Rivka Rubin Tautan', 'USD', false, 'Imported from CSV'),
  ('Sara Tovi', 'USD', false, 'Imported from CSV'),
  ('Rami Ben Nathan', 'USD', false, 'Imported from CSV'),
  ('Boaz Sokol', 'USD', false, 'Imported from CSV'),
  ('Udi Eyal Fima', 'USD', false, 'Imported from CSV'),
  ('Gabriel Szendro', 'USD', false, 'Imported from CSV'),
  ('Tomer Koko', 'USD', false, 'Imported from CSV'),
  ('Bar Shira', 'USD', false, 'Imported from CSV'),
  ('Eran Witkon', 'USD', false, 'Imported from CSV'),
  ('Ariel Eldar', 'USD', false, 'Imported from CSV'),
  ('Joseph Rosenblum', 'USD', false, 'Imported from CSV'),
  ('Avraham Cohen', 'USD', false, 'Imported from CSV'),
  ('Victorya Rofeim', 'USD', false, 'Imported from CSV'),
  ('Tziporet Koren', 'USD', false, 'Imported from CSV'),
  ('Nick Shrayer', 'USD', false, 'Imported from CSV'),
  ('Giora Erdinast', 'USD', false, 'Imported from CSV'),
  ('Miriam Attar', 'USD', false, 'Imported from CSV'),
  ('Ronen Moas', 'USD', false, 'Imported from CSV'),
  ('Eytan Dagry', 'USD', false, 'Imported from CSV'),
  ('Meir Steinbock', 'USD', false, 'Imported from CSV'),
  ('Marina Gurtin', 'USD', false, 'Imported from CSV'),
  ('Ron Yakir', 'USD', false, 'Imported from CSV'),
  ('Zeev Beer', 'USD', false, 'Imported from CSV'),
  ('Dror Paz', 'USD', false, 'Imported from CSV'),
  ('Amnon Shoham', 'USD', false, 'Imported from CSV'),
  ('Abraham Amos', 'USD', false, 'Imported from CSV'),
  ('Doron Peretz', 'USD', false, 'Imported from CSV'),
  ('Inon Beracha', 'USD', false, 'Imported from CSV'),
  ('Talia Yogev', 'USD', false, 'Imported from CSV'),
  ('Adi Mor', 'USD', false, 'Imported from CSV'),
  ('John Pomfret', 'USD', false, 'Imported from CSV'),
  ('Eilon Sharon', 'USD', false, 'Imported from CSV'),
  ('Lucy Shvarzman', 'USD', false, 'Imported from CSV'),
  ('Joseph Moshkovsky', 'USD', false, 'Imported from CSV'),
  ('Avraham Weiss', 'USD', false, 'Imported from CSV'),
  ('Yoram Levinson', 'USD', false, 'Imported from CSV'),
  ('Ran Feiwisch', 'USD', false, 'Imported from CSV'),
  ('James Cohen', 'USD', false, 'Imported from CSV'),
  ('Brittany Gale JHTC as Trustee', 'USD', false, 'Imported from CSV'),
  ('Eitan Antler', 'USD', false, 'Imported from CSV'),
  ('Uri Mishol', 'USD', false, 'Imported from CSV'),
  ('Rammy Bahalul', 'USD', false, 'Imported from CSV'),
  ('Zelman Fridman', 'USD', false, 'Imported from CSV'),
  ('Zion Ben Rafael', 'USD', false, 'Imported from CSV'),
  ('Shira Lichtenstadt', 'USD', false, 'Imported from CSV'),
  ('Chava Ben David', 'USD', false, 'Imported from CSV'),
  ('Ofra Rivlin', 'USD', false, 'Imported from CSV'),
  ('Marc Yoskowitz', 'USD', false, 'Imported from CSV'),
  ('Eytan Zucker', 'USD', false, 'Imported from CSV'),
  ('Edward Best', 'USD', false, 'Imported from CSV'),
  ('Bob Ciaruffoli', 'USD', false, 'Imported from CSV'),
  ('Niv Raviv', 'USD', false, 'Imported from CSV'),
  ('Elchanan Ashkenazi', 'USD', false, 'Imported from CSV'),
  ('David Cohen', 'USD', false, 'Imported from CSV'),
  ('Guy Levit', 'USD', false, 'Imported from CSV'),
  ('Assaf Ziv', 'USD', false, 'Imported from CSV'),
  ('Lior Goren', 'USD', false, 'Imported from CSV'),
  ('Shavit Fragman', 'USD', false, 'Imported from CSV'),
  ('Gal Israeli', 'USD', false, 'Imported from CSV'),
  ('Ido Warshavski', 'USD', false, 'Imported from CSV'),
  ('Roi Turgeman', 'USD', false, 'Imported from CSV'),
  ('Adi Zwickel', 'USD', false, 'Imported from CSV'),
  ('Amnon Fattal', 'USD', false, 'Imported from CSV'),
  ('Tamar Hirsh', 'USD', false, 'Imported from CSV'),
  ('Almog Shimon', 'USD', false, 'Imported from CSV'),
  ('Gil Kerbs', 'USD', false, 'Imported from CSV'),
  ('Matthew Duffy', 'USD', false, 'Imported from CSV'),
  ('Amir Rimon', 'USD', false, 'Imported from CSV'),
  ('Tamir Shabat', 'USD', false, 'Imported from CSV'),
  ('Hilla Mogilevsky', 'USD', false, 'Imported from CSV'),
  ('Kush Mirani', 'USD', false, 'Imported from CSV'),
  ('Lauren Wolff', 'USD', false, 'Imported from CSV'),
  ('Yigal Funt', 'USD', false, 'Imported from CSV'),
  ('Michael Melinger', 'USD', false, 'Imported from CSV'),
  ('Yishay Shachar', 'USD', false, 'Imported from CSV'),
  ('Elhanan Abramov', 'USD', false, 'Imported from CSV'),
  ('Tamir Bogin', 'USD', false, 'Imported from CSV'),
  ('Amnon Magnus', 'USD', false, 'Imported from CSV'),
  ('Mario Riello', 'USD', false, 'Imported from CSV'),
  ('Moshe Mashiach', 'USD', false, 'Imported from CSV'),
  ('Boaz Harel', 'USD', false, 'Imported from CSV'),
  ('Oren Kladnitsky', 'USD', false, 'Imported from CSV'),
  ('Arie Abramovitz', 'USD', false, 'Imported from CSV'),
  ('Amir Harush', 'USD', false, 'Imported from CSV'),
  ('Roy Gold', 'USD', false, 'Imported from CSV'),
  ('Yaniv Nissim', 'USD', false, 'Imported from CSV'),
  ('Alexander Shpiner', 'USD', false, 'Imported from CSV'),
  ('Sally Reidman', 'USD', false, 'Imported from CSV'),
  ('Rivka Kompel', 'USD', false, 'Imported from CSV'),
  ('Nimrod Zuta', 'USD', false, 'Imported from CSV'),
  ('Aviad Yehezkel', 'USD', false, 'Imported from CSV'),
  ('Keith Butler', 'USD', false, 'Imported from CSV'),
  ('Haim Alfandari', 'USD', false, 'Imported from CSV'),
  ('Eran Vakrat', 'USD', false, 'Imported from CSV'),
  ('Yuval Bryt', 'USD', false, 'Imported from CSV'),
  ('Alon Even', 'USD', false, 'Imported from CSV'),
  ('Ori Stav', 'USD', false, 'Imported from CSV'),
  ('Matan Ben Shaul', 'USD', false, 'Imported from CSV'),
  ('Ophir Turbovich', 'USD', false, 'Imported from CSV'),
  ('David Johnston', 'USD', false, 'Imported from CSV'),
  ('Tom Richter', 'USD', false, 'Imported from CSV'),
  ('Atai Levy', 'USD', false, 'Imported from CSV'),
  ('Giorah Levy', 'USD', false, 'Imported from CSV'),
  ('Jeffrey Aaron', 'USD', false, 'Imported from CSV'),
  ('Moshe Oz', 'USD', false, 'Imported from CSV'),
  ('Ronen Berkovich', 'USD', false, 'Imported from CSV'),
  ('Giora Bitan', 'USD', false, 'Imported from CSV'),
  ('Avraham Goldin', 'USD', false, 'Imported from CSV'),
  ('Jonathan Reis', 'USD', false, 'Imported from CSV'),
  ('Avner Fish', 'USD', false, 'Imported from CSV'),
  ('Edward Holland', 'USD', false, 'Imported from CSV'),
  ('Bar Halpert', 'USD', false, 'Imported from CSV'),
  ('Eyal Segal', 'USD', false, 'Imported from CSV'),
  ('Ravit Rosenberg', 'USD', false, 'Imported from CSV'),
  ('Dan Lishansky', 'USD', false, 'Imported from CSV'),
  ('Kenneth Boenish', 'USD', false, 'Imported from CSV'),
  ('Yaron Menashe', 'USD', false, 'Imported from CSV'),
  ('Dalit and Erez Mizrahi', 'USD', false, 'Imported from CSV'),
  ('Ilana Ben', 'USD', false, 'Imported from CSV'),
  ('Shay Berka', 'USD', false, 'Imported from CSV'),
  ('Shoval Tshuva', 'USD', false, 'Imported from CSV'),
  ('Itamar Roth', 'USD', false, 'Imported from CSV'),
  ('Eyal Ben Yehuda', 'USD', false, 'Imported from CSV'),
  ('Sagi Weinblat', 'USD', false, 'Imported from CSV'),
  ('Amitai Shaul', 'USD', false, 'Imported from CSV'),
  ('Ben Zion Bar', 'USD', false, 'Imported from CSV'),
  ('Michele Kaminsky', 'USD', false, 'Imported from CSV'),
  ('Jonathan Zamzok', 'USD', false, 'Imported from CSV'),
  ('Benjamin Silberman', 'USD', false, 'Imported from CSV'),
  ('Michal Hassner', 'USD', false, 'Imported from CSV'),
  ('Dotan Guy', 'USD', false, 'Imported from CSV'),
  ('Anat Madanes', 'USD', false, 'Imported from CSV'),
  ('Alon Ascher', 'USD', false, 'Imported from CSV'),
  ('Terry Dickerson', 'USD', false, 'Imported from CSV'),
  ('Nir Avraham', 'USD', false, 'Imported from CSV'),
  ('Lilach Shapira', 'USD', false, 'Imported from CSV'),
  ('Moshe Lasman', 'USD', false, 'Imported from CSV'),
  ('Haim Hoffman', 'USD', false, 'Imported from CSV'),
  ('Lisa Korn', 'USD', false, 'Imported from CSV'),
  ('Ronny Cohen', 'USD', false, 'Imported from CSV'),
  ('Nadine Gesundheit', 'USD', false, 'Imported from CSV'),
  ('Avner Shacham', 'USD', false, 'Imported from CSV'),
  ('Ran Avidan', 'USD', false, 'Imported from CSV'),
  ('Richard Bondie', 'USD', false, 'Imported from CSV'),
  ('Zeev Ariel', 'USD', false, 'Imported from CSV'),
  ('Moty Goren', 'USD', false, 'Imported from CSV'),
  ('Mordechai Serock', 'USD', false, 'Imported from CSV'),
  ('Sami Ekhaus', 'USD', false, 'Imported from CSV'),
  ('Moshe Graber', 'USD', false, 'Imported from CSV'),
  ('Sharon Goldstone', 'USD', false, 'Imported from CSV'),
  ('Eran Eden', 'USD', false, 'Imported from CSV'),
  ('Robert Quinn', 'USD', false, 'Imported from CSV'),
  ('Benny Pinkus', 'USD', false, 'Imported from CSV'),
  ('Tzvi Vainer', 'USD', false, 'Imported from CSV'),
  ('Fiona Rosenberg', 'USD', false, 'Imported from CSV'),
  ('Aviv Drori', 'USD', false, 'Imported from CSV'),
  ('Bronislav Doobrovsky', 'USD', false, 'Imported from CSV'),
  ('Saleet Granit', 'USD', false, 'Imported from CSV'),
  ('Gadi Shvarzman', 'USD', false, 'Imported from CSV'),
  ('Gregory Doobrovsky', 'USD', false, 'Imported from CSV'),
  ('Dov Fikler', 'USD', false, 'Imported from CSV'),
  ('Eitan Porat', 'USD', false, 'Imported from CSV'),
  ('Eylon Penchas', 'USD', false, 'Imported from CSV'),
  ('Matan Holander', 'USD', false, 'Imported from CSV'),
  ('Niv Zer', 'USD', false, 'Imported from CSV'),
  ('Naama Shmocher', 'USD', false, 'Imported from CSV'),
  ('Shlomo Hakim', 'USD', false, 'Imported from CSV'),
  ('Shlomo Avidar', 'USD', false, 'Imported from CSV'),
  ('Itzhak Blatt', 'USD', false, 'Imported from CSV'),
  ('Moshe Tsabari', 'USD', false, 'Imported from CSV'),
  ('Ofer Lowinger', 'USD', false, 'Imported from CSV'),
  ('Andrew Sucoff', 'USD', false, 'Imported from CSV'),
  ('David Melinger', 'USD', false, 'Imported from CSV'),
  ('Eliezer Oren', 'USD', false, 'Imported from CSV'),
  ('Ronen Soffer', 'USD', false, 'Imported from CSV'),
  ('Nathan Palanker', 'USD', false, 'Imported from CSV'),
  ('Moshe Lifschitz', 'USD', false, 'Imported from CSV'),
  ('Oren Wener', 'USD', false, 'Imported from CSV'),
  ('Adi Masad', 'USD', false, 'Imported from CSV'),
  ('Arie Cipris', 'USD', false, 'Imported from CSV'),
  ('Barry Finestone', 'USD', false, 'Imported from CSV'),
  ('Leora Silberg', 'USD', false, 'Imported from CSV'),
  ('Sharon Sheer', 'USD', false, 'Imported from CSV'),
  ('Gilad Kapelushnik', 'USD', false, 'Imported from CSV'),
  ('Yehonatan Hirshberg', 'USD', false, 'Imported from CSV'),
  ('Lior Levin', 'USD', false, 'Imported from CSV'),
  ('Ari Shore', 'USD', false, 'Imported from CSV'),
  ('Yaniv Vakrat', 'USD', false, 'Imported from CSV'),
  ('Joav Nachshon', 'USD', false, 'Imported from CSV'),
  ('Brendan Selway', 'USD', false, 'Imported from CSV'),
  ('Nir Hayzler', 'USD', false, 'Imported from CSV'),
  ('David Goldfeld', 'USD', false, 'Imported from CSV'),
  ('Nissim Moshe', 'USD', false, 'Imported from CSV'),
  ('Asher Holzer', 'USD', false, 'Imported from CSV'),
  ('Rafi Biton', 'USD', false, 'Imported from CSV'),
  ('Alon Kristal', 'USD', false, 'Imported from CSV'),
  ('Erez Kampel', 'USD', false, 'Imported from CSV'),
  ('Galit Nahmanzon', 'USD', false, 'Imported from CSV'),
  ('Lior Sagie', 'USD', false, 'Imported from CSV'),
  ('Shlomo Lifschitz', 'USD', false, 'Imported from CSV'),
  ('Mario Braun', 'USD', false, 'Imported from CSV'),
  ('Ran Shallish', 'USD', false, 'Imported from CSV'),
  ('Rebecca Mati', 'USD', false, 'Imported from CSV'),
  ('Asaf Vos', 'USD', false, 'Imported from CSV'),
  ('Simon Braun', 'USD', false, 'Imported from CSV'),
  ('Dafna Yankielowicz', 'USD', false, 'Imported from CSV'),
  ('Igal Nevo', 'USD', false, 'Imported from CSV'),
  ('Shirit Harpaz', 'USD', false, 'Imported from CSV'),
  ('Assaf Matityahu', 'USD', false, 'Imported from CSV'),
  ('Licia Hahn', 'USD', false, 'Imported from CSV'),
  ('Shay Zadok', 'USD', false, 'Imported from CSV'),
  ('Liran Serok', 'USD', false, 'Imported from CSV'),
  ('Assaf Korner', 'USD', false, 'Imported from CSV'),
  ('Ronen Shilo', 'USD', false, 'Imported from CSV'),
  ('Irad Yuval', 'USD', false, 'Imported from CSV'),
  ('David Stiefel', 'USD', false, 'Imported from CSV'),
  ('Pietro Sternini', 'USD', false, 'Imported from CSV'),
  ('Einav Itamar', 'USD', false, 'Imported from CSV'),
  ('Idan Grossman', 'USD', false, 'Imported from CSV'),
  ('Idit Harpaz', 'USD', false, 'Imported from CSV'),
  ('David Reznik', 'USD', false, 'Imported from CSV'),
  ('Gustav Stern', 'USD', false, 'Imported from CSV'),
  ('Guy Barnatan', 'USD', false, 'Imported from CSV'),
  ('Tal Gabay', 'USD', false, 'Imported from CSV'),
  ('Guy Morag', 'USD', false, 'Imported from CSV'),
  ('Efi Goren', 'USD', false, 'Imported from CSV'),
  ('Gene Dattel', 'USD', false, 'Imported from CSV'),
  ('Alain Goldschmidt', 'USD', false, 'Imported from CSV'),
  ('Axel Inon', 'USD', false, 'Imported from CSV'),
  ('Avraham Schwartz', 'USD', false, 'Imported from CSV'),
  ('Alevtina Stolpnik', 'USD', false, 'Imported from CSV'),
  ('Zeev Yahalom', 'USD', false, 'Imported from CSV'),
  ('Shlomoh Ben', 'USD', false, 'Imported from CSV'),
  ('Ehud Admoni', 'USD', false, 'Imported from CSV'),
  ('Rony Lev', 'USD', false, 'Imported from CSV'),
  ('Alexander Osherov', 'USD', false, 'Imported from CSV'),
  ('Ehud Almog', 'USD', false, 'Imported from CSV'),
  ('Marc Grossman', 'USD', false, 'Imported from CSV'),
  ('Yaniv Gavish', 'USD', false, 'Imported from CSV'),
  ('Roy Oron', 'USD', false, 'Imported from CSV'),
  ('Piero Marigo', 'USD', false, 'Imported from CSV'),
  ('David Perlmutter', 'USD', false, 'Imported from CSV'),
  ('Nissim Adar', 'USD', false, 'Imported from CSV'),
  ('Eyal Attia', 'USD', false, 'Imported from CSV'),
  ('Ori Ben Moshe', 'USD', false, 'Imported from CSV'),
  ('Tamir Azarzar', 'USD', false, 'Imported from CSV'),
  ('Jacob Verthaizer', 'USD', false, 'Imported from CSV'),
  ('Sharon Schweppe', 'USD', false, 'Imported from CSV'),
  ('Asaf Bareket', 'USD', false, 'Imported from CSV'),
  ('David Feiler', 'USD', false, 'Imported from CSV'),
  ('Jonah Bruck', 'USD', false, 'Imported from CSV'),
  ('Oren Lazarovich', 'USD', false, 'Imported from CSV'),
  ('Eran Tal', 'USD', false, 'Imported from CSV'),
  ('Michal Avtalion Rishony', 'USD', false, 'Imported from CSV'),
  ('Etty Schnitzer Neeman', 'USD', false, 'Imported from CSV'),
  ('Jakov Cohen', 'USD', false, 'Imported from CSV'),
  ('Oren Cohen', 'USD', false, 'Imported from CSV'),
  ('Yoav Levy', 'USD', false, 'Imported from CSV'),
  ('Ester Steinmetz Iny', 'USD', false, 'Imported from CSV'),
  ('Andrew Thompson', 'USD', false, 'Imported from CSV'),
  ('James Levine', 'USD', false, 'Imported from CSV'),
  ('Eran Regev', 'USD', false, 'Imported from CSV'),
  ('Eshel Bar', 'USD', false, 'Imported from CSV'),
  ('Jacob Horesh', 'USD', false, 'Imported from CSV'),
  ('Simon Stolero', 'USD', false, 'Imported from CSV'),
  ('Yoram Mehr', 'USD', false, 'Imported from CSV'),
  ('Zvi Genis', 'USD', false, 'Imported from CSV'),
  ('Arie Nadler', 'USD', false, 'Imported from CSV'),
  ('Eliyahou Kamhine', 'USD', false, 'Imported from CSV'),
  ('Noah Slimak', 'USD', false, 'Imported from CSV'),
  ('Eugenia Wolf', 'USD', false, 'Imported from CSV'),
  ('Yosef Michaeli', 'USD', false, 'Imported from CSV'),
  ('Matan Bichler', 'USD', false, 'Imported from CSV'),
  ('Gal Kampel', 'USD', false, 'Imported from CSV'),
  ('Jaacov BenJaacov', 'USD', false, 'Imported from CSV'),
  ('Yekutiel Raz', 'USD', false, 'Imported from CSV'),
  ('Galia Einav', 'USD', false, 'Imported from CSV'),
  ('Lidor Dvir', 'USD', false, 'Imported from CSV'),
  ('Tom Galili', 'USD', false, 'Imported from CSV'),
  ('Itamar Shafir', 'USD', false, 'Imported from CSV'),
  ('Alon Rabinovich', 'USD', false, 'Imported from CSV'),
  ('Ittai Golde', 'USD', false, 'Imported from CSV'),
  ('Matanya Bar', 'USD', false, 'Imported from CSV'),
  ('Ohad Reshef', 'USD', false, 'Imported from CSV'),
  ('Offer Yarkoni', 'USD', false, 'Imported from CSV'),
  ('Yoram Shalit', 'USD', false, 'Imported from CSV'),
  ('Tomer Schlussel', 'USD', false, 'Imported from CSV'),
  ('Yehoshua Weiss', 'USD', false, 'Imported from CSV'),
  ('Gila Ben David', 'USD', false, 'Imported from CSV'),
  ('Yaniv Dar', 'USD', false, 'Imported from CSV'),
  ('Stephen Tanzer', 'USD', false, 'Imported from CSV'),
  ('Refael Yerushalmi', 'USD', false, 'Imported from CSV'),
  ('Tomer Dalumi', 'USD', false, 'Imported from CSV'),
  ('Ron Schechter', 'USD', false, 'Imported from CSV'),
  ('Guy Elbaz', 'USD', false, 'Imported from CSV'),
  ('Amir Grimberg', 'USD', false, 'Imported from CSV'),
  ('Meir Nachshon', 'USD', false, 'Imported from CSV'),
  ('Yoram Nagelstein', 'USD', false, 'Imported from CSV'),
  ('Leeraz Rousseau', 'USD', false, 'Imported from CSV'),
  ('Nir Jacoel', 'USD', false, 'Imported from CSV'),
  ('Tal Weissman', 'USD', false, 'Imported from CSV'),
  ('Gershon Schnider', 'USD', false, 'Imported from CSV'),
  ('Evyatar Sagie', 'USD', false, 'Imported from CSV'),
  ('Mordechai Orenstein', 'USD', false, 'Imported from CSV'),
  ('Gali Stamler', 'USD', false, 'Imported from CSV'),
  ('Sagi Hakmon', 'USD', false, 'Imported from CSV'),
  ('Shai Reuven', 'USD', false, 'Imported from CSV'),
  ('Dror Shomrat', 'USD', false, 'Imported from CSV'),
  ('Tal Feigel', 'USD', false, 'Imported from CSV'),
  ('Ehud Goren', 'USD', false, 'Imported from CSV'),
  ('David Gilat', 'USD', false, 'Imported from CSV'),
  ('David Furman', 'USD', false, 'Imported from CSV'),
  ('Eyal Halimi', 'USD', false, 'Imported from CSV'),
  ('Elisheva Margulies', 'USD', false, 'Imported from CSV'),
  ('Daniel Macadar', 'USD', false, 'Imported from CSV'),
  ('Sarah Ann Margulies', 'USD', false, 'Imported from CSV'),
  ('Shantam Zohar', 'USD', false, 'Imported from CSV'),
  ('Daniel Shalev', 'USD', false, 'Imported from CSV'),
  ('Eyal Gutman', 'USD', false, 'Imported from CSV'),
  ('Igor Lotsvin', 'USD', false, 'Imported from CSV'),
  ('David Weinberger', 'USD', false, 'Imported from CSV'),
  ('Hilla Lavi', 'USD', false, 'Imported from CSV'),
  ('Rafael Aravot', 'USD', false, 'Imported from CSV'),
  ('Yariv Haelyon', 'USD', false, 'Imported from CSV'),
  ('Yaron Hertz', 'USD', false, 'Imported from CSV'),
  ('Aryeh Stern', 'USD', false, 'Imported from CSV'),
  ('Yehuda Mayshar', 'USD', false, 'Imported from CSV'),
  ('Jacob Sabo', 'USD', false, 'Imported from CSV'),
  ('Yigal Pergamentzev', 'USD', false, 'Imported from CSV'),
  ('Operations team Conscientia Family Office', 'USD', false, 'Imported from CSV'),
  ('Matan Groen', 'USD', false, 'Imported from CSV'),
  ('Jonathan Avni', 'USD', false, 'Imported from CSV'),
  ('Yohay Ben Itzhak', 'USD', false, 'Imported from CSV'),
  ('Ofer Iny', 'USD', false, 'Imported from CSV'),
  ('Oded Morag', 'USD', false, 'Imported from CSV'),
  ('Nadav Golander', 'USD', false, 'Imported from CSV'),
  ('Amir Novik', 'USD', false, 'Imported from CSV'),
  ('Noga Shteinboim Atsil', 'USD', false, 'Imported from CSV'),
  ('Leonard Eis', 'USD', false, 'Imported from CSV'),
  ('Almog Chen', 'USD', false, 'Imported from CSV'),
  ('Netanella Tani Zahavi', 'USD', false, 'Imported from CSV'),
  ('Menahem Stein', 'USD', false, 'Imported from CSV'),
  ('Alik Rozenberg', 'USD', false, 'Imported from CSV'),
  ('Ron Konigsberg', 'USD', false, 'Imported from CSV'),
  ('Roi Caspi', 'USD', false, 'Imported from CSV'),
  ('Adam Abrams', 'USD', false, 'Imported from CSV'),
  ('Yair Peled', 'USD', false, 'Imported from CSV'),
  ('Yael Sade', 'USD', false, 'Imported from CSV'),
  ('Pinchas Gdaliahu', 'USD', false, 'Imported from CSV'),
  ('Elad Levi', 'USD', false, 'Imported from CSV'),
  ('David Goder', 'USD', false, 'Imported from CSV'),
  ('Gilad Slonim', 'USD', false, 'Imported from CSV'),
  ('Liron Polkovski', 'USD', false, 'Imported from CSV'),
  ('Alexander Partin', 'USD', false, 'Imported from CSV'),
  ('Shlomo Tamir', 'USD', false, 'Imported from CSV'),
  ('Ori Kaufman Gafter', 'USD', false, 'Imported from CSV'),
  ('Yee Jiun Song', 'USD', false, 'Imported from CSV'),
  ('Irvin Wiesman', 'USD', false, 'Imported from CSV'),
  ('Orit Kolonimus', 'USD', false, 'Imported from CSV'),
  ('Michelle Maack', 'USD', false, 'Imported from CSV'),
  ('Dalia Shalit', 'USD', false, 'Imported from CSV'),
  ('Atalia Katz', 'USD', false, 'Imported from CSV'),
  ('Meirav Dvash', 'USD', false, 'Imported from CSV'),
  ('Yaron Shohat', 'USD', false, 'Imported from CSV'),
  ('Alexander Herman', 'USD', false, 'Imported from CSV'),
  ('Ofer Lux', 'USD', false, 'Imported from CSV'),
  ('Mati Johananoff', 'USD', false, 'Imported from CSV'),
  ('Kefir Sade', 'USD', false, 'Imported from CSV'),
  ('Anat Haramati', 'USD', false, 'Imported from CSV'),
  ('Lior Sharon', 'USD', false, 'Imported from CSV'),
  ('Allan Barkat', 'USD', false, 'Imported from CSV'),
  ('Shlomit Zamir', 'USD', false, 'Imported from CSV'),
  ('Einat Barzilai', 'USD', false, 'Imported from CSV'),
  ('Eran Ben Yehuda', 'USD', false, 'Imported from CSV'),
  ('Ronen and Elynne Gold', 'USD', false, 'Imported from CSV'),
  ('Anatoliy Neymark', 'USD', false, 'Imported from CSV'),
  ('Omri Kaftzan', 'USD', false, 'Imported from CSV'),
  ('Doron Navati', 'USD', false, 'Imported from CSV'),
  ('Aviv Kfir', 'USD', false, 'Imported from CSV'),
  ('Shirley Schwartz', 'USD', false, 'Imported from CSV'),
  ('Yigal Jacoby', 'USD', false, 'Imported from CSV'),
  ('Maury Zeff', 'USD', false, 'Imported from CSV'),
  ('Michael Rosenfeld', 'USD', false, 'Imported from CSV'),
  ('Adi Grinberg', 'USD', false, 'Imported from CSV'),
  ('Ophir Eis', 'USD', false, 'Imported from CSV'),
  ('Irene Rosenthal', 'USD', false, 'Imported from CSV'),
  ('David Michaeli', 'USD', false, 'Imported from CSV'),
  ('Doron Rivlin', 'USD', false, 'Imported from CSV'),
  ('James Bogin', 'USD', false, 'Imported from CSV'),
  ('Aharon Rasouli', 'USD', false, 'Imported from CSV'),
  ('Eric Gagnon', 'USD', false, 'Imported from CSV'),
  ('Gad Novak', 'USD', false, 'Imported from CSV'),
  ('Harel Beit On', 'USD', false, 'Imported from CSV'),
  ('Avi Zeevi', 'USD', false, 'Imported from CSV'),
  ('Baruch Lerner', 'USD', false, 'Imported from CSV'),
  ('Orit Noked', 'USD', false, 'Imported from CSV'),
  ('Roie Sagi', 'USD', false, 'Imported from CSV'),
  ('Shlomo Liran', 'USD', false, 'Imported from CSV'),
  ('David Ezra', 'USD', false, 'Imported from CSV'),
  ('Ran Heilpern', 'USD', false, 'Imported from CSV'),
  ('Ido Luski', 'USD', false, 'Imported from CSV'),
  ('Monica DeFruscio', 'USD', false, 'Imported from CSV'),
  ('Oren Pereg', 'USD', false, 'Imported from CSV'),
  ('Eli David', 'USD', false, 'Imported from CSV'),
  ('David Truzman', 'USD', false, 'Imported from CSV'),
  ('Yuval Malka', 'USD', false, 'Imported from CSV'),
  ('Yuval Meidar', 'USD', false, 'Imported from CSV'),
  ('Steven Lavin', 'USD', false, 'Imported from CSV'),
  ('Alexander Goudz', 'USD', false, 'Imported from CSV'),
  ('Tal Rivkind', 'USD', false, 'Imported from CSV'),
  ('Abraham Fisher', 'USD', false, 'Imported from CSV'),
  ('Alex Shapira', 'USD', false, 'Imported from CSV'),
  ('Abraham Havron', 'USD', false, 'Imported from CSV'),
  ('Adva Mendelson', 'USD', false, 'Imported from CSV'),
  ('Abraham Peri', 'USD', false, 'Imported from CSV'),
  ('Sylvie Tovy', 'USD', false, 'Imported from CSV'),
  ('Adam Stramwasser', 'USD', false, 'Imported from CSV'),
  ('Boaz Shiponi', 'USD', false, 'Imported from CSV'),
  ('Yuval Harary', 'USD', false, 'Imported from CSV'),
  ('Yael Strauss', 'USD', false, 'Imported from CSV'),
  ('Tova Even Chen', 'USD', false, 'Imported from CSV'),
  ('Craig Harrison', 'USD', false, 'Imported from CSV'),
  ('Corine Kuperzsmidt', 'USD', false, 'Imported from CSV'),
  ('Tzuriel Katoa', 'USD', false, 'Imported from CSV'),
  ('Aviv Oranim', 'USD', false, 'Imported from CSV'),
  ('Yair Walker', 'USD', false, 'Imported from CSV'),
  ('Avner Shaul', 'USD', false, 'Imported from CSV'),
  ('Tzvia Frank', 'USD', false, 'Imported from CSV'),
  ('Asaf Shaltiel', 'USD', false, 'Imported from CSV'),
  ('Ayelet Arouh', 'USD', false, 'Imported from CSV'),
  ('Chen Carmel', 'USD', false, 'Imported from CSV'),
  ('Yael Holdengreber', 'USD', false, 'Imported from CSV'),
  ('Chana Rav Acha', 'USD', false, 'Imported from CSV'),
  ('Chaim Oren', 'USD', false, 'Imported from CSV'),
  ('Batya Marks', 'USD', false, 'Imported from CSV'),
  ('William Bermont', 'USD', false, 'Imported from CSV'),
  ('Demetrius Nonas', 'USD', false, 'Imported from CSV'),
  ('Arnold Kostman', 'USD', false, 'Imported from CSV'),
  ('Yudith Sarfaty', 'USD', false, 'Imported from CSV'),
  ('Amnon Kaydar', 'USD', false, 'Imported from CSV'),
  ('Yossef Kasus', 'USD', false, 'Imported from CSV'),
  ('Yosi Shiloni', 'USD', false, 'Imported from CSV'),
  ('Amir Azia', 'USD', false, 'Imported from CSV'),
  ('Yoram Yohanani', 'USD', false, 'Imported from CSV'),
  ('Amit Flohr', 'USD', false, 'Imported from CSV'),
  ('Yoram Burg', 'USD', false, 'Imported from CSV'),
  ('Amit Reichman', 'USD', false, 'Imported from CSV'),
  ('Tanhum Oren', 'USD', false, 'Imported from CSV'),
  ('Ari', 'USD', false, 'Imported from CSV'),
  ('Boaz Israeli', 'USD', false, 'Imported from CSV'),
  ('Yizchak Zuriel', 'USD', false, 'Imported from CSV'),
  ('David Elalouf', 'USD', false, 'Imported from CSV'),
  ('Darius Mirshahzadeh', 'USD', false, 'Imported from CSV'),
  ('Yinon Kuperstein', 'USD', false, 'Imported from CSV'),
  ('Andy Reiken', 'USD', false, 'Imported from CSV'),
  ('Daniel Magen', 'USD', false, 'Imported from CSV'),
  ('Anat Kaluzshner', 'USD', false, 'Imported from CSV'),
  ('Aaron Epstein', 'USD', false, 'Imported from CSV'),
  ('Lior Martin', 'USD', false, 'Imported from CSV'),
  ('Ron Guttmann', 'USD', false, 'Imported from CSV'),
  ('Niv Taiber', 'USD', false, 'Imported from CSV'),
  ('Lavi Cohen', 'USD', false, 'Imported from CSV'),
  ('Guy Shaviv', 'USD', false, 'Imported from CSV'),
  ('Niv Hanan', 'USD', false, 'Imported from CSV'),
  ('Guy Mandel', 'USD', false, 'Imported from CSV'),
  ('Roee Vulkan', 'USD', false, 'Imported from CSV'),
  ('Lea Preminger', 'USD', false, 'Imported from CSV'),
  ('Roi Zemmer', 'USD', false, 'Imported from CSV'),
  ('Nisim Segalovich', 'USD', false, 'Imported from CSV'),
  ('Lena Oren', 'USD', false, 'Imported from CSV'),
  ('Leslie Epstein', 'USD', false, 'Imported from CSV'),
  ('Ron Hartston', 'USD', false, 'Imported from CSV'),
  ('Richard Blau', 'USD', false, 'Imported from CSV'),
  ('Liat Herman', 'USD', false, 'Imported from CSV'),
  ('Gordon Schwartz', 'USD', false, 'Imported from CSV'),
  ('Jeffrey Theobald', 'USD', false, 'Imported from CSV'),
  ('Ronen Barak', 'USD', false, 'Imported from CSV'),
  ('Ginat Zilberstein', 'USD', false, 'Imported from CSV'),
  ('Gila Hakhami', 'USD', false, 'Imported from CSV'),
  ('Ronen Waisserberg', 'USD', false, 'Imported from CSV'),
  ('Nathan Aronovici', 'USD', false, 'Imported from CSV'),
  ('George Kreisberg', 'USD', false, 'Imported from CSV'),
  ('Geffen Oren', 'USD', false, 'Imported from CSV'),
  ('Gal Mor', 'USD', false, 'Imported from CSV'),
  ('Rina Avraham', 'USD', false, 'Imported from CSV'),
  ('Judy Mozes', 'USD', false, 'Imported from CSV'),
  ('Maon Jacobson', 'USD', false, 'Imported from CSV'),
  ('Oded Margalit', 'USD', false, 'Imported from CSV'),
  ('Jetash Gangwal', 'USD', false, 'Imported from CSV'),
  ('Or Peri', 'USD', false, 'Imported from CSV'),
  ('James DeFalco', 'USD', false, 'Imported from CSV'),
  ('Omer Belsky', 'USD', false, 'Imported from CSV'),
  ('Oren Mendelson', 'USD', false, 'Imported from CSV'),
  ('Jacob Yaniv', 'USD', false, 'Imported from CSV'),
  ('Jacob Herzmann', 'USD', false, 'Imported from CSV'),
  ('Jacob Assif', 'USD', false, 'Imported from CSV'),
  ('Orit Nir', 'USD', false, 'Imported from CSV'),
  ('Ivan Facianof', 'USD', false, 'Imported from CSV'),
  ('Ofir Rozenfeld', 'USD', false, 'Imported from CSV'),
  ('Irit Stern', 'USD', false, 'Imported from CSV'),
  ('Rebecca Brown', 'USD', false, 'Imported from CSV'),
  ('Irit Gillath', 'USD', false, 'Imported from CSV'),
  ('Joseph Hasten', 'USD', false, 'Imported from CSV'),
  ('Irad Ratmansky', 'USD', false, 'Imported from CSV'),
  ('Iliya Gurevich', 'USD', false, 'Imported from CSV'),
  ('Ilan Atias', 'USD', false, 'Imported from CSV'),
  ('Rami Lazar', 'USD', false, 'Imported from CSV'),
  ('Ido Tenne', 'USD', false, 'Imported from CSV'),
  ('Joseph Johananoff', 'USD', false, 'Imported from CSV'),
  ('Idan Kornfeld', 'USD', false, 'Imported from CSV'),
  ('Joshua Sherbin', 'USD', false, 'Imported from CSV'),
  ('Ran Shevi', 'USD', false, 'Imported from CSV'),
  ('Gal Levinsky', 'USD', false, 'Imported from CSV'),
  ('Jeremy Goldberg', 'USD', false, 'Imported from CSV'),
  ('Sharon Wagner', 'USD', false, 'Imported from CSV'),
  ('Edward Parkansky', 'USD', false, 'Imported from CSV'),
  ('Margaret Frank', 'USD', false, 'Imported from CSV'),
  ('Moshe Dovev', 'USD', false, 'Imported from CSV'),
  ('Efraim Grynberg', 'USD', false, 'Imported from CSV'),
  ('Meytal Schwartz', 'USD', false, 'Imported from CSV'),
  ('Shlomo Waldmann', 'USD', false, 'Imported from CSV'),
  ('Matthew Rosenbluth', 'USD', false, 'Imported from CSV'),
  ('Merav Axelrod', 'USD', false, 'Imported from CSV'),
  ('Mickey Hanegbee Kaplinsky', 'USD', false, 'Imported from CSV'),
  ('Menahem Wirtzburg', 'USD', false, 'Imported from CSV'),
  ('Meir Rozolio', 'USD', false, 'Imported from CSV'),
  ('Eitan Cohen', 'USD', false, 'Imported from CSV'),
  ('Shalom Hochman', 'USD', false, 'Imported from CSV'),
  ('Shany Alon', 'USD', false, 'Imported from CSV'),
  ('Shay Shevi', 'USD', false, 'Imported from CSV'),
  ('Eli Grinberg', 'USD', false, 'Imported from CSV'),
  ('Sarah Pavoncello', 'USD', false, 'Imported from CSV'),
  ('Schmuel Grizim', 'USD', false, 'Imported from CSV'),
  ('Ephraim Cohen', 'USD', false, 'Imported from CSV'),
  ('Sagi Matas', 'USD', false, 'Imported from CSV'),
  ('Shoshana Kremer', 'USD', false, 'Imported from CSV'),
  ('Eddi Haddad', 'USD', false, 'Imported from CSV'),
  ('Gai Berkovich', 'USD', false, 'Imported from CSV'),
  ('Gal Hassid', 'USD', false, 'Imported from CSV'),
  ('Michal Blumenstyk', 'USD', false, 'Imported from CSV'),
  ('Michal Shohat', 'USD', false, 'Imported from CSV'),
  ('Mark Lippman', 'USD', false, 'Imported from CSV'),
  ('Michael Wahrhaft', 'USD', false, 'Imported from CSV'),
  ('Shmuel Parag', 'USD', false, 'Imported from CSV'),
  ('Moshe Ran', 'USD', false, 'Imported from CSV'),
  ('Dov Blatt', 'USD', false, 'Imported from CSV'),
  ('Yuval Kamhi', 'USD', false, 'Imported from CSV'),
  ('Amit Porat', 'USD', false, 'Imported from CSV'),
  ('Gal Kats', 'USD', false, 'Imported from CSV'),
  ('Robert Wizenberg', 'USD', false, 'Imported from CSV'),
  ('Ran Machtinger', 'USD', false, 'Imported from CSV'),
  ('Tal Edelman', 'USD', false, 'Imported from CSV'),
  ('Frank Cortese', 'USD', false, 'Imported from CSV'),
  ('Joseph Sergi', 'USD', false, 'Imported from CSV'),
  ('Lior Alon', 'USD', false, 'Imported from CSV'),
  ('Tom Livne', 'USD', false, 'Imported from CSV'),
  ('Amit Birk', 'USD', false, 'Imported from CSV'),
  ('Oron Stern', 'USD', false, 'Imported from CSV'),
  ('Tzachi Ben Itzhak', 'USD', false, 'Imported from CSV'),
  ('Mordechay Eliyahoo', 'USD', false, 'Imported from CSV'),
  ('Ilan Jacobson', 'USD', false, 'Imported from CSV'),
  ('Ronen Yablon', 'USD', false, 'Imported from CSV'),
  ('Yehezkel Schwartz', 'USD', false, 'Imported from CSV'),
  ('Mordechai Peled', 'USD', false, 'Imported from CSV'),
  ('Oren Sagi', 'USD', false, 'Imported from CSV'),
  ('David Levine', 'USD', false, 'Imported from CSV'),
  ('Cliff Joyner', 'USD', false, 'Imported from CSV'),
  ('Shlomo Latinik', 'USD', false, 'Imported from CSV'),
  ('Ron Preis', 'USD', false, 'Imported from CSV'),
  ('Kiran Tatiparthi', 'USD', false, 'Imported from CSV'),
  ('Sharon Finkel', 'USD', false, 'Imported from CSV'),
  ('Sofia Kimerling', 'USD', false, 'Imported from CSV'),
  ('Nathan Ron', 'USD', false, 'Imported from CSV'),
  ('Oren Mangel', 'USD', false, 'Imported from CSV'),
  ('Shai Meirson', 'USD', false, 'Imported from CSV'),
  ('Isaac Castiel', 'USD', false, 'Imported from CSV'),
  ('Colleen Covington', 'USD', false, 'Imported from CSV'),
  ('Alon Markus', 'USD', false, 'Imported from CSV'),
  ('Yakov Machluf', 'USD', false, 'Imported from CSV'),
  ('Shai Bazak', 'USD', false, 'Imported from CSV'),
  ('Justin Zale', 'USD', false, 'Imported from CSV'),
  ('Elhanan Borenstein', 'USD', false, 'Imported from CSV'),
  ('Ofir Yosef', 'USD', false, 'Imported from CSV'),
  ('Ilan Kedem', 'USD', false, 'Imported from CSV'),
  ('Naomi Avitan', 'USD', false, 'Imported from CSV'),
  ('Abe Schear', 'USD', false, 'Imported from CSV'),
  ('Michael Maman', 'USD', false, 'Imported from CSV'),
  ('Lior Meron', 'USD', false, 'Imported from CSV'),
  ('Manly Taylor Brown', 'USD', false, 'Imported from CSV'),
  ('Miri Rozenfeld', 'USD', false, 'Imported from CSV'),
  ('Mark Rosenberg', 'USD', false, 'Imported from CSV'),
  ('Amy Stern', 'USD', false, 'Imported from CSV'),
  ('Jonathan Mann', 'USD', false, 'Imported from CSV'),
  ('Ofer Miller', 'USD', false, 'Imported from CSV'),
  ('Jonathan Mor', 'USD', false, 'Imported from CSV'),
  ('Zeevik Kopatz', 'USD', false, 'Imported from CSV'),
  ('Oded Fuchs', 'USD', false, 'Imported from CSV'),
  ('Moran Bar', 'USD', false, 'Imported from CSV'),
  ('Mor Shvarzman', 'USD', false, 'Imported from CSV'),
  ('Amir Even Chen', 'USD', false, 'Imported from CSV'),
  ('Joseph Shine', 'USD', false, 'Imported from CSV'),
  ('Karthikeyan Thanikachalam', 'USD', false, 'Imported from CSV'),
  ('Joshua Mor', 'USD', false, 'Imported from CSV'),
  ('Dolphin Munzer', 'USD', false, 'Imported from CSV'),
  ('Ido Dvash', 'USD', false, 'Imported from CSV'),
  ('Yishai Fuchs', 'USD', false, 'Imported from CSV'),
  ('Shlomi Zac', 'USD', false, 'Imported from CSV'),
  ('Tamar Golan', 'USD', false, 'Imported from CSV'),
  ('Hadas Shabat', 'USD', false, 'Imported from CSV'),
  ('Emanuel Parter', 'USD', false, 'Imported from CSV'),
  ('Guy Raveh', 'USD', false, 'Imported from CSV'),
  ('Barden Brown', 'USD', false, 'Imported from CSV'),
  ('Yaakov Ringler', 'USD', false, 'Imported from CSV'),
  ('Guy Amit', 'USD', false, 'Imported from CSV'),
  ('Ron Golan', 'USD', false, 'Imported from CSV'),
  ('Eran Wolf', 'USD', false, 'Imported from CSV'),
  ('Tianyu Wang', 'USD', false, 'Imported from CSV'),
  ('Victor Levitan', 'USD', false, 'Imported from CSV'),
  ('Erez Noked', 'USD', false, 'Imported from CSV'),
  ('Daniel Peretz', 'USD', false, 'Imported from CSV'),
  ('Chandler Brown', 'USD', false, 'Imported from CSV'),
  ('Gil Bigon', 'USD', false, 'Imported from CSV'),
  ('Christina Rozen', 'USD', false, 'Imported from CSV'),
  ('Coral Kuperman', 'USD', false, 'Imported from CSV'),
  ('Tzipora Carmon', 'USD', false, 'Imported from CSV'),
  ('Cory Sams', 'USD', false, 'Imported from CSV'),
  ('Sean Shvarzman', 'USD', false, 'Imported from CSV'),
  ('Ezra Werubel', 'USD', false, 'Imported from CSV'),
  ('Scott Perlen', 'USD', false, 'Imported from CSV'),
  ('Shirley Gal', 'USD', false, 'Imported from CSV'),
  ('Haim Jacob', 'USD', false, 'Imported from CSV'),
  ('David Litvak', 'USD', false, 'Imported from CSV'),
  ('Oren Ifrach', 'USD', false, 'Imported from CSV'),
  ('Ori Tuval', 'USD', false, 'Imported from CSV'),
  ('Ariel Efrati', 'USD', false, 'Imported from CSV'),
  ('Douglas Goldsmith', 'USD', false, 'Imported from CSV'),
  ('David Schifter', 'USD', false, 'Imported from CSV'),
  ('Arik Ben Dor', 'USD', false, 'Imported from CSV'),
  ('Ory Milleau', 'USD', false, 'Imported from CSV'),
  ('Israel Gruber', 'USD', false, 'Imported from CSV'),
  ('Douglas Ross', 'USD', false, 'Imported from CSV'),
  ('Iris Cohen', 'USD', false, 'Imported from CSV'),
  ('Pinhas Gaist', 'USD', false, 'Imported from CSV'),
  ('Rachel Gafni', 'USD', false, 'Imported from CSV'),
  ('Ido Leonov', 'USD', false, 'Imported from CSV'),
  ('Avichai Cohen', 'USD', false, 'Imported from CSV'),
  ('Ian Jasenof', 'USD', false, 'Imported from CSV'),
  ('Hilli Peri', 'USD', false, 'Imported from CSV'),
  ('Aviv Shapira', 'USD', false, 'Imported from CSV'),
  ('Dan Shachtman', 'USD', false, 'Imported from CSV'),
  ('Spencer Green', 'USD', false, 'Imported from CSV'),
  ('Joseph Liran', 'USD', false, 'Imported from CSV'),
  ('Ron Zetouni', 'USD', false, 'Imported from CSV'),
  ('Nissim Bar', 'USD', false, 'Imported from CSV'),
  ('Tal Even', 'USD', false, 'Imported from CSV'),
  ('Ben Amrami', 'USD', false, 'Imported from CSV'),
  ('John DeFalco', 'USD', false, 'Imported from CSV'),
  ('Michael Shless', 'USD', false, 'Imported from CSV'),
  ('Rona', 'USD', false, 'Imported from CSV'),
  ('Omri Liba', 'USD', false, 'Imported from CSV'),
  ('Rephael Germon', 'USD', false, 'Imported from CSV'),
  ('Samuel Zell', 'USD', false, 'Imported from CSV'),
  ('Yuval Terem', 'USD', false, 'Imported from CSV'),
  ('Jonathan Aaron', 'USD', false, 'Imported from CSV'),
  ('Itamar Dach', 'USD', false, 'Imported from CSV'),
  ('Yaniv Levi', 'USD', false, 'Imported from CSV'),
  ('Hadas Sparfeld', 'USD', false, 'Imported from CSV'),
  ('Nir Fux', 'USD', false, 'Imported from CSV'),
  ('Walter Miller', 'USD', false, 'Imported from CSV'),
  ('David Donenberg', 'USD', false, 'Imported from CSV'),
  ('Tobey Sheridan', 'USD', false, 'Imported from CSV'),
  ('Megan Hall', 'USD', false, 'Imported from CSV'),
  ('Chanan Schneider', 'USD', false, 'Imported from CSV'),
  ('Robert Hodge', 'USD', false, 'Imported from CSV'),
  ('Haidee Chiat', 'USD', false, 'Imported from CSV'),
  ('Paul Aiesi', 'USD', false, 'Imported from CSV'),
  ('Yosef Barazani', 'USD', false, 'Imported from CSV')
ON CONFLICT (name) DO NOTHING;

-- Verification: Check investor count
-- SELECT COUNT(*) FROM investors;

-- ============================================
-- INSERT DEALS (if they don't exist)
-- Note: Deals without fund_id will need to be updated later
-- ============================================
INSERT INTO deals (name, status, close_date)
VALUES
  ('BULCC LLC', 'Active', NULL),
  ('BULMF LLC', 'Active', NULL),
  ('West Coast Land Ventures LLC', 'Active', NULL),
  ('Marquis Crest Buligo LP', 'Active', NULL),
  ('Providence Plaza Buligo LP', 'Active', NULL),
  ('Columbus Buligo I', 'Active', NULL),
  ('LP', 'Active', NULL),
  ('Autumn Ridge Buligo LP', 'Active', NULL),
  ('Central Governors Buligo LP', 'Active', NULL),
  ('193 Henry Buligo LP', 'Active', NULL),
  ('160 West Saddle Rock Loan', 'Active', NULL),
  ('Cera 1', 'Active', NULL),
  ('Barcelona LP', 'Active', NULL),
  ('West Side Plaza Buligo LP', 'Active', NULL),
  ('Compton House Developments Limited', 'Active', NULL),
  ('Metro Portfolio Buligo LP', 'Active', NULL),
  ('160 West Saddle Rock Loan 2', 'Active', NULL),
  ('Murrells Buligo LP', 'Active', NULL),
  ('MGB Private Equity Investments', 'Active', NULL),
  ('S.L', 'Active', NULL),
  ('Golomb 40', 'Active', NULL),
  ('Belaire Buligo LP', 'Active', NULL),
  ('Dania Beach Buligo LP', 'Active', NULL),
  ('Ryans Crossing Buligo LP', 'Active', NULL),
  ('Lafayette Buligo LP', 'Active', NULL),
  ('Neely Ferry Buligo LP', 'Active', NULL),
  ('Calle d''Arta', 'Active', NULL),
  ('Limited Partnership', 'Active', NULL),
  ('Vine Street Square Buligo LP', 'Active', NULL),
  ('Enterprise Plaza Buligo LP', 'Active', NULL),
  ('Beaufort Buligo LP', 'Active', NULL),
  ('Reigo Investments LLC', 'Active', NULL),
  ('Autumn Ridge Junior Loan', 'Active', NULL),
  ('White House Buligo LP', 'Active', NULL),
  ('Roper Mountain Buligo LP', 'Active', NULL),
  ('Ellijay Buligo LP', 'Active', NULL),
  ('Autumn Ridge Junior Loan 2', 'Active', NULL),
  ('Temple Terrace Plaza', 'Active', NULL),
  ('Kenall Buligo LP', 'Active', NULL),
  ('Golomb 40 Refinance', 'Active', NULL),
  ('Ironwood Buligo LP', 'Active', NULL),
  ('Reigo Senior Secured Loans LLC', 'Active', NULL),
  ('Nostrand Place Buligo LP', 'Active', NULL),
  ('Dawsonville Buligo LP', 'Active', NULL),
  ('Belaire Junior Loan', 'Active', NULL),
  ('Cera 1 Loan 3', 'Active', NULL),
  ('STG Buligo LLC', 'Active', NULL),
  ('Hoschton Buligo LP', 'Active', NULL),
  ('Leland Apartments Buligo LP', 'Active', NULL),
  ('Oak Brook Buligo LP', 'Active', NULL),
  ('Eagle Buligo LP', 'Active', NULL),
  ('Antioch Buligo LP', 'Active', NULL),
  ('Weaverville Plaza Buligo LP', 'Active', NULL),
  ('Reserve Buligo LP', 'Active', NULL),
  ('Ciutat 13', 'Active', NULL),
  ('Barcelona LP Loan', 'Active', NULL),
  ('Contguard Ltd.', 'Active', NULL),
  ('131 Devoe St Member Loan 2', 'Active', NULL),
  ('Hamilton Mill Buligo LP', 'Active', NULL),
  ('Tribute Buligo LP', 'Active', NULL),
  ('Barak Dagon Loan', 'Active', NULL),
  ('Urbandale Buligo LP', 'Active', NULL),
  ('Encore Buligo LP', 'Active', NULL),
  ('Lullwater Buligo LP', 'Active', NULL),
  ('Osceola Village Buligo LP', 'Active', NULL),
  ('Milagro Buligo LP', 'Active', NULL),
  ('Via Buligo LP', 'Active', NULL),
  ('Manor Lake Athens Loan', 'Active', NULL),
  ('Neely Ferry Phase II Buligo LP', 'Active', NULL),
  ('Greenway Buligo LP', 'Active', NULL),
  ('Midtown Buligo LP', 'Active', NULL),
  ('Remez 5', 'Active', NULL),
  ('Roswell Buligo LP', 'Active', NULL),
  ('Reigo Securitization I LP', 'Active', NULL),
  ('571 Commerce Buligo LP', 'Active', NULL),
  ('Parkwood Buligo LP', 'Active', NULL),
  ('Lullwater II Buligo LP', 'Active', NULL),
  ('Dania Beach II Buligo LP', 'Active', NULL),
  ('Cartersville Buligo LP', 'Active', NULL),
  ('Ciutat 13 Member Loan', 'Active', NULL),
  ('Arnica Inc.', 'Active', NULL),
  ('Osborne Buligo LP', 'Active', NULL),
  ('Hickory Flat Buligo LP', 'Active', NULL),
  ('Fox Buligo LP', 'Active', NULL),
  ('Aventine Buligo LP', 'Active', NULL),
  ('Pencil Buligo LP', 'Active', NULL),
  ('216 Cedar Avenue Loan', 'Active', NULL),
  ('Tyde Buligo LP', 'Active', NULL),
  ('Red Willow Buligo LP', 'Active', NULL),
  ('Retreat at Weaverville Buligo LP', 'Active', NULL),
  ('Manor Lake Dawsonville Loan', 'Active', NULL),
  ('5949 Jackson Road', 'Active', NULL),
  ('Skyline Buligo LP', 'Active', NULL),
  ('1010 Buligo LP', 'Active', NULL),
  ('CLI Buligo LP', 'Active', NULL),
  ('Westgate Buligo LP', 'Active', NULL),
  ('McGaw Court Buligo LP', 'Active', NULL),
  ('Huntsville Buligo LP', 'Active', NULL),
  ('Riverside at Whitehall Buligo LP', 'Active', NULL),
  ('Autumn Ridge Junior Loan 3', 'Active', NULL),
  ('Berwick Buligo LP', 'Active', NULL),
  ('Cheshire Buligo LP', 'Active', NULL),
  ('Dry Creek Buligo LP', 'Active', NULL),
  ('Bay Road Buligo LP', 'Active', NULL),
  ('Perdido Buligo LP', 'Active', NULL),
  ('Flat Rock Buligo LP', 'Active', NULL),
  ('Classic City Flats Buligo LP', 'Active', NULL),
  ('Thatcher Woods Buligo LP', 'Active', NULL),
  ('6501 Nevada Buligo LP', 'Active', NULL),
  ('East Hennepin Buligo LP', 'Active', NULL),
  ('Johnstown Buligo LP', 'Active', NULL),
  ('Brentwood Buligo LP', 'Active', NULL),
  ('Snellville Buligo LP', 'Active', NULL),
  ('Parkwood Loan', 'Active', NULL),
  ('Eagle Member Loan', 'Active', NULL),
  ('Ciutat 13 Member Loan 1', 'Active', NULL),
  ('Groton Square Buligo LP', 'Active', NULL),
  ('9231 Penn Ave Buligo LP', 'Active', NULL),
  ('Riverwood Buligo LP', 'Active', NULL),
  ('Gainesville 2023 Buligo LP', 'Active', NULL),
  ('Hartford Buligo LP', 'Active', NULL),
  ('201 Triple Diamond Buligo LP', 'Active', NULL),
  ('Mason Buligo LP', 'Active', NULL),
  ('Weaverville Loan', 'Active', NULL),
  ('Bridge Mill Investor Sr Loan LLC', 'Active', NULL),
  ('Ellijay Loan', 'Active', NULL),
  ('Eagle Sr Loan', 'Active', NULL),
  ('2840 W Orange Ave Buligo LP', 'Active', NULL),
  ('River Ridge 2023 Buligo LP', 'Active', NULL),
  ('Tyde Buligo LP - Loan', 'Active', NULL),
  ('Neely Ferry Buligo LP - Loan', 'Active', NULL),
  ('Pencil Loan', 'Active', NULL),
  ('Manor Lake Athens Loan - February 2024', 'Active', NULL),
  ('Fitzroy Buligo LP', 'Active', NULL),
  ('10793 Harry Hines Buligo LP', 'Active', NULL),
  ('Statesboro Buligo LP', 'Active', NULL),
  ('Reems Creek Buligo LP', 'Active', NULL),
  ('1000 W Crosby Buligo LP', 'Active', NULL),
  ('5 East Pointe Drive Buligo LP', 'Active', NULL),
  ('Oakwood Buligo LP', 'Active', NULL),
  ('Sugarloaf Buligo LP', 'Active', NULL),
  ('Hudson Buligo LP', 'Active', NULL),
  ('Hoschton IL Buligo LP', 'Active', NULL),
  ('Johnstown Loan', 'Active', NULL),
  ('1302 Eastport Road Buligo LP', 'Active', NULL),
  ('310 Tyson Drive Buligo LP', 'Active', NULL),
  ('310 Tyson Drive Operating LP', 'Active', NULL),
  ('Hiram 2024 Buligo LP', 'Active', NULL),
  ('Tyde II Buligo LP', 'Active', NULL),
  ('Sunbelt MOB 1 Buligo LP', 'Active', NULL),
  ('Parkwood Loan - March 2025', 'Active', NULL),
  ('Ledge Rock Apartments I Buligo LP', 'Active', NULL),
  ('Highline Buligo LP', 'Active', NULL),
  ('Eagle Loan - May 2025', 'Active', NULL),
  ('Sarasota Shallow Bay Buligo LP', 'Active', NULL),
  ('Sarasota Shallow Bay SKN LP', 'Active', NULL),
  ('100 City View Buligo LP', 'Active', NULL),
  ('Manchac and Odyssey Buligo LP', 'Active', NULL),
  ('Manchac Operating LP', 'Active', NULL),
  ('Odyssey Business Park Operating LP', 'Active', NULL),
  ('Total', 'Active', NULL),
  ('Sea Palms Buligo LP', 'Active', NULL),
  ('Fairview Park Buligo LP', 'Active', NULL),
  ('Haverly Buligo LP', 'Active', NULL),
  ('Gardens at Ashley Buligo LP', 'Active', NULL),
  ('Farrington Buligo LP', 'Active', NULL),
  ('Pontevedra–Baluard', 'Active', NULL),
  ('Barceloneta- LP', 'Active', NULL),
  ('Hibernia Buligo LP', 'Active', NULL),
  ('River Ridge Buligo LP', 'Active', NULL),
  ('Oakview Park Buligo LP', 'Active', NULL),
  ('Meadows Buligo LP', 'Active', NULL),
  ('Winters Creek Buligo LP', 'Active', NULL),
  ('Tree Trail Buligo LP', 'Active', NULL),
  ('Lloret', 'Active', NULL),
  ('Gateway Buligo LP', 'Active', NULL),
  ('Sant Magi', 'Active', NULL),
  ('Toledo 87', 'Active', NULL),
  ('Madrid', 'Active', NULL),
  ('Walden Oaks Buligo LP', 'Active', NULL),
  ('Fairview Park ILF Buligo LP', 'Active', NULL),
  ('Gainesville Buligo LP', 'Active', NULL),
  ('Cotton Mill Buligo LP', 'Active', NULL),
  ('Waterford Buligo LP', 'Active', NULL),
  ('Ascent 430 Buligo LP', 'Active', NULL),
  ('Christina Mill Buligo LP', 'Active', NULL),
  ('Duncan Buligo LP', 'Active', NULL),
  ('Athens Buligo LP', 'Active', NULL),
  ('CP Phase II Buligo LP', 'Active', NULL),
  ('Belaire Junior Loan 2', 'Active', NULL),
  ('Buligo IRA Fund I LP', 'Active', NULL),
  ('Eagle IRA Fund I LP', 'Active', NULL),
  ('Buligo IRA Fund II LP', 'Active', NULL),
  ('Milagro IRA Fund I LP', 'Active', NULL),
  ('Meitav Buligo IRA Fund I LP', 'Active', NULL),
  ('Dry Creek IRA Fund I LP', 'Active', NULL),
  ('Perdido IRA Fund I LP', 'Active', NULL),
  ('Buligo Fund IV IRA LP', 'Active', NULL),
  ('Mason IRA Fund I LP', 'Active', NULL),
  ('River Ridge 2023 IRA Fund I LP', 'Active', NULL),
  ('Buligo Fund V Cayman IRA LP', 'Active', NULL),
  ('Tyde Preferred IRA Fund I LP', 'Active', NULL),
  ('Buligo Fund VI IRA LP', 'Active', NULL),
  ('ACR', 'Active', NULL),
  ('Stone Crossing Buligo LP', 'Active', NULL),
  ('277 East 7th Buligo LP', 'Active', NULL),
  ('Stephen Plant', 'Active', NULL),
  ('Devcor Properties Limited', 'Active', NULL),
  ('Azalea Hill Buligo LP', 'Active', NULL),
  ('STSB Real Estate LLC', 'Active', NULL),
  ('GrayBul Summer Chase Apts LP', 'Active', NULL),
  ('Spring Park Buligo LP', 'Active', NULL),
  ('Spring Park Junior Loan', 'Active', NULL),
  ('Litchfield Oaks Buligo LP', 'Active', NULL),
  ('Lincoln Springs Buligo LP', 'Active', NULL),
  ('Woods Edge Buligo LP', 'Active', NULL),
  ('277 East 7th Loan', 'Active', NULL),
  ('Closegate Hotel Development (Durham) Limited', 'Active', NULL),
  ('Ashley Woods Buligo LP', 'Active', NULL),
  ('Towerview Buligo LP', 'Active', NULL),
  ('Charleston Buligo LP', 'Active', NULL),
  ('160 West Buligo LP', 'Active', NULL),
  ('Spartanburg Buligo LP', 'Active', NULL),
  ('Weldon and Popat', 'Active', NULL),
  ('Tanya Frayne', 'Active', NULL),
  ('De Guardia Building Barcelona', 'Active', NULL),
  ('Parkwest Buligo LP', 'Active', NULL),
  ('Sherwood Ridges Buligo LP', 'Active', NULL),
  ('160 West Guarantee', 'Active', NULL),
  ('160 West Member Loan', 'Active', NULL),
  ('Royal Plaza Buligo LP', 'Active', NULL),
  ('Closegate Hotel Development (Durham) Limited (Refinance)', 'Active', NULL),
  ('Arcadia Developments Limited', 'Active', NULL),
  ('Dash/Buligo 24 LP', 'Active', NULL),
  ('GSE Waterbrook Limited', 'Active', NULL),
  ('Thomas Rooney', 'Active', NULL),
  ('China Hotel Buligo LP', 'Active', NULL),
  ('North Second Street Limited', 'Active', NULL),
  ('Itamar 4', 'Active', NULL),
  ('Mansfield', 'Active', NULL),
  ('Tarana International', 'Active', NULL),
  ('Fairview Village Buligo LP', 'Active', NULL),
  ('131 Devoe Preferred Equity Loan', 'Active', NULL),
  ('131 Devoe Preferred Equity Loan 1A', 'Active', NULL),
  ('131 Devoe Buligo LP', 'Active', NULL),
  ('Bridge Mill Buligo LP', 'Active', NULL),
  ('Crescent Buligo LP', 'Active', NULL),
  ('131 Devoe St Member Loan', 'Active', NULL),
  ('Lincoln Springs Junior Loan', 'Active', NULL),
  ('Hiram Buligo LP', 'Active', NULL),
  ('Pond Bay Buligo LP', 'Active', NULL),
  ('AMC Trust', 'Active', NULL),
  ('BULCC Loan', 'Active', NULL),
  ('GSE Cheriton Parc', 'Active', NULL),
  ('ABC13313 – Maria Arceo', 'Active', NULL),
  ('Primesite Student Ltd', 'Active', NULL),
  ('BridgeMill Junior Loan', 'Active', NULL),
  ('Manor Lake Gainesville Junior Loan', 'Active', NULL),
  ('Orencel Tamarind', 'Active', NULL),
  ('LLC', 'Active', NULL),
  ('Cotton Mill - Roberto Slimak', 'Active', NULL),
  ('131 Devoe Guarantee', 'Active', NULL),
  ('Bundeep Rangar', 'Active', NULL),
  ('Woodcroft', 'Active', NULL),
  ('Woodcroft Refinance', 'Active', NULL),
  ('Buligo Fund IV INDIV LP', 'Active', NULL),
  ('Buligo Fund V INDIV LP', 'Active', NULL),
  ('ECA BULIGO PARKWEST CROSSING', 'Active', NULL),
  ('ECA Buligo Providence Partners', 'Active', NULL),
  ('Barceloneta- LP Loan', 'Active', NULL),
  ('Cera 1 Loan', 'Active', NULL),
  ('Cera 1 Loan 2', 'Active', NULL),
  ('277 East 7th (Steven Ball)', 'Active', NULL),
  ('North Second Street Limited Refinance', 'Active', NULL),
  ('Meitav Buligo Fund I LP', 'Active', NULL),
  ('Maria Arceo', 'Active', NULL),
  ('131 Devoe Preferred Equity Loan 2', 'Active', NULL),
  ('Vulcan RE Capital LLC', 'Active', NULL),
  ('Chartwell Asset Management Limited', 'Active', NULL),
  ('Buligo Fund VI INDIV LP', 'Active', NULL),
  ('Buligo Fund V Cayman LP', 'Active', NULL),
  ('Rainbul-Farrington LP Loan', 'Active', NULL)
ON CONFLICT (name) DO NOTHING;

-- Verification: Check deal count
-- SELECT COUNT(*) FROM deals;

-- ============================================
-- Summary
-- ============================================
-- Total investors to insert: 1390
-- Total deals to insert: 282
-- Use ON CONFLICT DO NOTHING to skip duplicates

