// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwgicrdcoqdketqhxbys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Z2ljcmRjb3Fka2V0cWh4YnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjYzMDcsImV4cCI6MjA3MjgwMjMwN30.6PZnjAcRXYcd_sNZHb6ZDxyg914JMtkCtqIYvHt3P1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Auth guard: handle invalid refresh tokens
supabase.auth.onAuthStateChange(async (event, session) => {
  // Ignore successful token refresh
  if (event === 'TOKEN_REFRESHED') return;
  if (event === 'SIGNED_OUT') return;

  // If we have no session and event is not a sign-out, clear any stale data
  if (!session && event === 'USER_UPDATED') {
    // Session expired - will be handled by http.ts 401 handler
    console.warn('Session expired, user will be redirected to login on next API call');
  }
});